package dc.visao.comercial;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.comercial.TipoNotaFiscalFormController;
import dc.visao.framework.util.ComponentUtil;
import dc.visao.suprimentos.ContagemEstoqueFormController;

public class TipoNotaFiscalFormView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	TipoNotaFiscalFormController controller;

	@AutoGenerated
	private GridLayout fields;
	
	private TextField txtModelo;
	
	private TextField txtSerie;
	
	private TextField txtNome;
	

	public TipoNotaFiscalFormView(TipoNotaFiscalFormController controller) {
		this.controller = controller;
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		fields = buildFields();
		mainLayout.addComponent(fields);
		
		return mainLayout;

	}

	@AutoGenerated
	private GridLayout buildFields() {
		// common part: create layout
		fields = new GridLayout(6, 1);
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		
		txtModelo = ComponentUtil.buildTextField("Modelo");
		fields.addComponent(txtModelo,0,0);
		
		txtSerie = ComponentUtil.buildTextField("Série");
		fields.addComponent(txtModelo,1,0);
		
		txtNome = ComponentUtil.buildTextField("Nome");
		fields.addComponent(txtModelo,2,0);
        return fields;
	}
}