package dc.visao.comercial;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.comercial.TipoNotaFiscalFormController;
import dc.visao.framework.util.ComponentUtil;
import dc.visao.suprimentos.ContagemEstoqueFormController;

public class TipoNotaFiscalFormView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	TipoNotaFiscalFormController controller;

	@AutoGenerated
	private GridLayout fields;
	
	private TextField txtModelo;
	
	private TextField txtSerie;
	
	private TextField txtNome,txtDescricao;
	
	private TextField txtTemplate,txtNumeroItens,txtUltimoImpresso;
	

	public TipoNotaFiscalFormView(TipoNotaFiscalFormController controller) {
		this.controller = controller;
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		fields = buildFields();
		mainLayout.addComponent(fields);
		
		return mainLayout;

	}

	@AutoGenerated
	private GridLayout buildFields() {
		// common part: create layout
		fields = new GridLayout(6, 6);
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		
		txtNome = ComponentUtil.buildTextField("Nome");
		txtNome.setRequired(true);
	     fields.addComponent(txtNome,0,0);
	     
	    txtDescricao = ComponentUtil.buildTextField("Descrição");
	    fields.addComponent(txtDescricao,1,0,4,0);
	    		 
		txtModelo = ComponentUtil.buildTextField("Modelo");
		txtModelo.setMaxLength(2);
		fields.addComponent(txtModelo,0,1);
		
		txtSerie = ComponentUtil.buildTextField("Série");
		txtSerie.setMaxLength(3);
		fields.addComponent(txtSerie,1,1);
		
		txtTemplate = ComponentUtil.buildTextField("Template");
		fields.addComponent(txtTemplate,2,1);
		
		txtNumeroItens = ComponentUtil.buildNumericField("Número Itens");
		fields.addComponent(txtNumeroItens,3,1);
		
		txtUltimoImpresso = ComponentUtil.buildNumericField("Último Impresso");
		fields.addComponent(txtUltimoImpresso,4,1);
		
		return fields;
			
	}

	public TextField getTxtModelo() {
		return txtModelo;
	}

	public void setTxtModelo(TextField txtModelo) {
		this.txtModelo = txtModelo;
	}

	public TextField getTxtSerie() {
		return txtSerie;
	}

	public void setTxtSerie(TextField txtSerie) {
		this.txtSerie = txtSerie;
	}

	public TextField getTxtNome() {
		return txtNome;
	}

	public void setTxtNome(TextField txtNome) {
		this.txtNome = txtNome;
	}

	public TextField getTxtDescricao() {
		return txtDescricao;
	}

	public void setTxtDescricao(TextField txtDescricao) {
		this.txtDescricao = txtDescricao;
	}

	public TextField getTxtTemplate() {
		return txtTemplate;
	}

	public void setTxtTemplate(TextField txtTemplate) {
		this.txtTemplate = txtTemplate;
	}

	public TextField getTxtNumeroItens() {
		return txtNumeroItens;
	}

	public void setTxtNumeroItens(TextField txtNumeroItens) {
		this.txtNumeroItens = txtNumeroItens;
	}

	public TextField getTxtUltimoImpresso() {
		return txtUltimoImpresso;
	}

	public void setTxtUltimoImpresso(TextField txtUltimoImpresso) {
		this.txtUltimoImpresso = txtUltimoImpresso;
	}
	
	
}