package dc.visao.suprimentos.compra;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.suprimentos.compra.TipoPedidoFormController;
import dc.visao.framework.util.ComponentUtil;

public class TipoPedidoFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private VerticalLayout vlGeral;

	@AutoGenerated
	private Panel plGeral;

	@AutoGenerated
	private GridLayout glGeral;

	@AutoGenerated
	private TextField tfCodigo;

	@AutoGenerated
	private TextField tfDescricao;

	@AutoGenerated
	private TextField tfNome;

	private TipoPedidoFormController controller;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public TipoPedidoFormView(TipoPedidoFormController controller) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.controller = controller;
	}

	public TextField getTfCodigo() {
		return tfCodigo;
	}

	public void setTfCodigo(TextField tfCodigo) {
		this.tfCodigo = tfCodigo;
	}

	public TextField getTfDescricao() {
		return tfDescricao;
	}

	public void setTfDescricao(TextField tfDescricao) {
		this.tfDescricao = tfDescricao;
	}

	public TextField getTfNome() {
		return tfNome;
	}

	public void setTfNome(TextField tfNome) {
		this.tfNome = tfNome;
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		mainLayout.addComponent(bvlGeral());
	}

	@AutoGenerated
	public VerticalLayout bvlGeral() {
		// common part: create layout
		vlGeral = new VerticalLayout();
		vlGeral.setImmediate(false);
		vlGeral.setWidth("100.0%");
		vlGeral.setHeight("100.0%");
		vlGeral.setMargin(true);
		vlGeral.setSpacing(true);
		// vlGeral.setCaption("Cliente");

		//
		vlGeral.addComponent(bplGeral());

		return vlGeral;
	}

	@AutoGenerated
	private Panel bplGeral() {
		// common part: create layout
		plGeral = new Panel();
		plGeral.setImmediate(false);
		plGeral.setSizeFull();

		//
		plGeral.setContent(bglGeral());

		return plGeral;
	}

	@AutoGenerated
	private GridLayout bglGeral() {
		glGeral = new GridLayout();
		glGeral.setImmediate(false);
		glGeral.setWidth("100.0%");
		glGeral.setMargin(true);
		glGeral.setSpacing(true);
		glGeral.setRows(6);
		glGeral.setColumns(1);

		// tfCodigo
		tfCodigo = ComponentUtil.buildTextField("Código");
		glGeral.addComponent(tfCodigo, 0, 0);

		// tfNome
		tfNome = ComponentUtil.buildTextField("Nome");
		glGeral.addComponent(tfNome, 0, 1);

		// tfDescricao
		tfDescricao = ComponentUtil.buildTextField("Descrição");
		glGeral.addComponent(tfDescricao, 0, 2);

		return glGeral;
	}

}