package dc.visao.produto;

import org.vaadin.tepi.imageviewer.ImageViewer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;

import dc.entidade.diversos.Almoxarifado;
import dc.entidade.produto.MarcaProduto;
import dc.entidade.produto.SubGrupoProduto;
import dc.entidade.produto.UnidadeProduto;
import dc.entidade.tributario.GrupoTributario;
import dc.visao.framework.component.manytoonecombo.ManyToOneCombo;

public class ProdutoFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_4;
	@AutoGenerated
	private TextField txtAliquotaICms;
	@AutoGenerated
	private TextField txtAliquotaIssqn;
	@AutoGenerated
	private TextField txtLoteEconomicoCompra;
	@AutoGenerated
	private TextField txtPontoPedido;
	@AutoGenerated
	private TextField txtTaxaComissao;
	@AutoGenerated
	private TextField txtPeso;
	@AutoGenerated
	private TextField txtCodigoBalanca;
	@AutoGenerated
	private TextField txtTotalizadorParcial;
	@AutoGenerated
	private ComboBox cmbTipoItemSped;
	@AutoGenerated
	private ComboBox cmbIppt;
	@AutoGenerated
	private ComboBox cmbIat;
	@AutoGenerated
	private ComboBox cmbTipo;
	@AutoGenerated
	private TextField txtExtipi;
	@AutoGenerated
	private TextField txtLst;
	@AutoGenerated
	private ImageViewer imgProduto;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	@AutoGenerated
	private TextField txtEstoqueMaximo;
	@AutoGenerated
	private TextField txtEstoqueMinimo;
	@AutoGenerated
	private TextField txtEstoqueIdeal;
	@AutoGenerated
	private TextField txtQtde;
	@AutoGenerated
	private TextField txtQuantidadeEstoque;
	@AutoGenerated
	private TextField txtMarkup;
	@AutoGenerated
	private TextField txtPrecoLucroMaximo;
	@AutoGenerated
	private TextField txtPrecoLucroMinimo;
	@AutoGenerated
	private TextField txtPrecoLucroZero;
	@AutoGenerated
	private TextField txtCustoMedioLiquido;
	@AutoGenerated
	private TextField txtValorSugerido;
	@AutoGenerated
	private TextField txtValorVendaMinimo;
	@AutoGenerated
	private TextField txtValorVenda;
	@AutoGenerated
	private TextField txtValorCompra;
	@AutoGenerated
	private TextField txtDescricao;
	@AutoGenerated
	private TextField txtDescricaoPdv;
	@AutoGenerated
	private TextField txtNome;
	@AutoGenerated
	private ComboBox cmbClasse;
	@AutoGenerated
	private ComboBox cmbInativo;
	@AutoGenerated
	private ComboBox cmbNcm;
	@AutoGenerated
	private TextField txtCodigoInterno;
	@AutoGenerated
	private TextField txtGtin;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private ComboBox cmbIcmsCustomizado;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	
	
	
	
	private ManyToOneCombo<UnidadeProduto> cmbUnidadeProduto;
	private ManyToOneCombo<MarcaProduto> cmbMarcaProduto;
	private ManyToOneCombo<Almoxarifado> cmbAlmoxarifado;
	private ManyToOneCombo<GrupoTributario> cmbGrupoTributario;
	private ManyToOneCombo<SubGrupoProduto> cmbSubGrupoProduto;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ProdutoFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public GridLayout getMainLayout() {
		return mainLayout;
	}

	public void setMainLayout(GridLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

	public AbsoluteLayout getAbsoluteLayout_2() {
		return absoluteLayout_2;
	}

	public void setAbsoluteLayout_2(AbsoluteLayout absoluteLayout_2) {
		this.absoluteLayout_2 = absoluteLayout_2;
	}

	public TabSheet getTabSheet_1() {
		return tabSheet_1;
	}

	public void setTabSheet_1(TabSheet tabSheet_1) {
		this.tabSheet_1 = tabSheet_1;
	}

	public AbsoluteLayout getAbsoluteLayout_4() {
		return absoluteLayout_4;
	}

	public void setAbsoluteLayout_4(AbsoluteLayout absoluteLayout_4) {
		this.absoluteLayout_4 = absoluteLayout_4;
	}

	public TextField getTxtAliquotaICms() {
		return txtAliquotaICms;
	}

	public void setTxtAliquotaICms(TextField txtAliquotaICms) {
		this.txtAliquotaICms = txtAliquotaICms;
	}

	public TextField getTxtAliquotaIssqn() {
		return txtAliquotaIssqn;
	}

	public void setTxtAliquotaIssqn(TextField txtAliquotaIssqn) {
		this.txtAliquotaIssqn = txtAliquotaIssqn;
	}

	public TextField getTxtLoteEconomicoCompra() {
		return txtLoteEconomicoCompra;
	}

	public void setTxtLoteEconomicoCompra(TextField txtLoteEconomicoCompra) {
		this.txtLoteEconomicoCompra = txtLoteEconomicoCompra;
	}

	public TextField getTxtPontoPedido() {
		return txtPontoPedido;
	}

	public void setTxtPontoPedido(TextField txtPontoPedido) {
		this.txtPontoPedido = txtPontoPedido;
	}

	public TextField getTxtTaxaComissao() {
		return txtTaxaComissao;
	}

	public void setTxtTaxaComissao(TextField txtTaxaComissao) {
		this.txtTaxaComissao = txtTaxaComissao;
	}

	public TextField getTxtPeso() {
		return txtPeso;
	}

	public void setTxtPeso(TextField txtPeso) {
		this.txtPeso = txtPeso;
	}

	public TextField getTxtCodigoBalanca() {
		return txtCodigoBalanca;
	}

	public void setTxtCodigoBalanca(TextField txtCodigoBalanca) {
		this.txtCodigoBalanca = txtCodigoBalanca;
	}

	public TextField getTxtTotalizadorParcial() {
		return txtTotalizadorParcial;
	}

	public void setTxtTotalizadorParcial(TextField txtTotalizadorParcial) {
		this.txtTotalizadorParcial = txtTotalizadorParcial;
	}

	public TextField getTxtExtipi() {
		return txtExtipi;
	}

	public void setTxtExtipi(TextField txtExtipi) {
		this.txtExtipi = txtExtipi;
	}

	public TextField getTxtLst() {
		return txtLst;
	}

	public void setTxtLst(TextField txtLst) {
		this.txtLst = txtLst;
	}

	public ImageViewer getImgProduto() {
		return imgProduto;
	}

	public void setImgProduto(ImageViewer imgProduto) {
		this.imgProduto = imgProduto;
	}

	public AbsoluteLayout getAbsoluteLayout_3() {
		return absoluteLayout_3;
	}

	public void setAbsoluteLayout_3(AbsoluteLayout absoluteLayout_3) {
		this.absoluteLayout_3 = absoluteLayout_3;
	}

	public TextField getTxtEstoqueMaximo() {
		return txtEstoqueMaximo;
	}

	public void setTxtEstoqueMaximo(TextField txtEstoqueMaximo) {
		this.txtEstoqueMaximo = txtEstoqueMaximo;
	}

	public TextField getTxtEstoqueMinimo() {
		return txtEstoqueMinimo;
	}

	public void setTxtEstoqueMinimo(TextField txtEstoqueMinimo) {
		this.txtEstoqueMinimo = txtEstoqueMinimo;
	}

	public TextField getTxtEstoqueIdeal() {
		return txtEstoqueIdeal;
	}

	public void setTxtEstoqueIdeal(TextField txtEstoqueIdeal) {
		this.txtEstoqueIdeal = txtEstoqueIdeal;
	}

	public TextField getTxtQtde() {
		return txtQtde;
	}

	public void setTxtQtde(TextField txtQtde) {
		this.txtQtde = txtQtde;
	}

	public TextField getTxtQuantidadeEstoque() {
		return txtQuantidadeEstoque;
	}

	public void setTxtQuantidadeEstoque(TextField txtQuantidadeEstoque) {
		this.txtQuantidadeEstoque = txtQuantidadeEstoque;
	}

	public TextField getTxtMarkup() {
		return txtMarkup;
	}

	public void setTxtMarkup(TextField txtMarkup) {
		this.txtMarkup = txtMarkup;
	}

	public TextField getTxtPrecoLucroMaximo() {
		return txtPrecoLucroMaximo;
	}

	public void setTxtPrecoLucroMaximo(TextField txtPrecoLucroMaximo) {
		this.txtPrecoLucroMaximo = txtPrecoLucroMaximo;
	}

	public TextField getTxtPrecoLucroMinimo() {
		return txtPrecoLucroMinimo;
	}

	public void setTxtPrecoLucroMinimo(TextField txtPrecoLucroMinimo) {
		this.txtPrecoLucroMinimo = txtPrecoLucroMinimo;
	}

	public TextField getTxtPrecoLucroZero() {
		return txtPrecoLucroZero;
	}

	public void setTxtPrecoLucroZero(TextField txtPrecoLucroZero) {
		this.txtPrecoLucroZero = txtPrecoLucroZero;
	}

	public TextField getTxtCustoMedioLiquido() {
		return txtCustoMedioLiquido;
	}

	public void setTxtCustoMedioLiquido(TextField txtCustoMedioLiquido) {
		this.txtCustoMedioLiquido = txtCustoMedioLiquido;
	}

	public TextField getTxtValorSugerido() {
		return txtValorSugerido;
	}

	public void setTxtValorSugerido(TextField txtValorSugerido) {
		this.txtValorSugerido = txtValorSugerido;
	}

	public TextField getTxtValorVendaMinimo() {
		return txtValorVendaMinimo;
	}

	public void setTxtValorVendaMinimo(TextField txtValorVendaMinimo) {
		this.txtValorVendaMinimo = txtValorVendaMinimo;
	}

	public TextField getTxtValorVenda() {
		return txtValorVenda;
	}

	public void setTxtValorVenda(TextField txtValorVenda) {
		this.txtValorVenda = txtValorVenda;
	}

	public TextField getTxtValorCompra() {
		return txtValorCompra;
	}

	public void setTxtValorCompra(TextField txtValorCompra) {
		this.txtValorCompra = txtValorCompra;
	}

	public TextField getTxtDescricao() {
		return txtDescricao;
	}

	public void setTxtDescricao(TextField txtDescricao) {
		this.txtDescricao = txtDescricao;
	}

	public TextField getTxtDescricaoPdv() {
		return txtDescricaoPdv;
	}

	public void setTxtDescricaoPdv(TextField txtDescricaoPdv) {
		this.txtDescricaoPdv = txtDescricaoPdv;
	}

	public TextField getTxtNome() {
		return txtNome;
	}

	public void setTxtNome(TextField txtNome) {
		this.txtNome = txtNome;
	}

	public ComboBox getCmbNcm() {
		return cmbNcm;
	}

	public void setCmbNcm(ComboBox cmbNcm) {
		this.cmbNcm = cmbNcm;
	}

	public TextField getTxtCodigoInterno() {
		return txtCodigoInterno;
	}

	public void setTxtCodigoInterno(TextField txtCodigoInterno) {
		this.txtCodigoInterno = txtCodigoInterno;
	}

	public TextField getTxtGtin() {
		return txtGtin;
	}

	public void setTxtGtin(TextField txtGtin) {
		this.txtGtin = txtGtin;
	}

	public HorizontalLayout getHorizontalLayout_2() {
		return horizontalLayout_2;
	}

	public void setHorizontalLayout_2(HorizontalLayout horizontalLayout_2) {
		this.horizontalLayout_2 = horizontalLayout_2;
	}

	public HorizontalLayout getHorizontalLayout_1() {
		return horizontalLayout_1;
	}

	public void setHorizontalLayout_1(HorizontalLayout horizontalLayout_1) {
		this.horizontalLayout_1 = horizontalLayout_1;
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		mainLayout.setRows(3);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, 0, 0);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2, 0, 1);
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2, 0, 2);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// cmbUnidadeProduto
		cmbUnidadeProduto = new ManyToOneCombo<>();
		cmbUnidadeProduto.setCaption("Unidade Produto");
		cmbUnidadeProduto.setImmediate(false);
		cmbUnidadeProduto.setWidth("494px");
		cmbUnidadeProduto.setHeight("-1px");
		horizontalLayout_1.addComponent(cmbUnidadeProduto);
		
		// cmbSubGrupoProduto
		cmbSubGrupoProduto = new ManyToOneCombo<>();
		cmbSubGrupoProduto.setCaption("Sub Grupo Produto");
		cmbSubGrupoProduto.setImmediate(false);
		cmbSubGrupoProduto.setWidth("456px");
		cmbSubGrupoProduto.setHeight("-1px");
		horizontalLayout_1.addComponent(cmbSubGrupoProduto);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// cmbMarcaProduto
		cmbMarcaProduto = new ManyToOneCombo<>();
		cmbMarcaProduto.setCaption("Marca Produto");
		cmbMarcaProduto.setImmediate(false);
		cmbMarcaProduto.setWidth("320px");
		cmbMarcaProduto.setHeight("-1px");
		horizontalLayout_2.addComponent(cmbMarcaProduto);
		
		// cmbAlmoxarifado
		cmbAlmoxarifado = new ManyToOneCombo<>();
		cmbAlmoxarifado.setCaption("Almoxarifado");
		cmbAlmoxarifado.setImmediate(false);
		cmbAlmoxarifado.setWidth("254px");
		cmbAlmoxarifado.setHeight("-1px");
		horizontalLayout_2.addComponent(cmbAlmoxarifado);
		
		// cmbIcmsCustomizado
		cmbIcmsCustomizado = new ComboBox();
		cmbIcmsCustomizado.setCaption("ICMS Customizado?");
		cmbIcmsCustomizado.setImmediate(false);
		cmbIcmsCustomizado.setWidth("134px");
		cmbIcmsCustomizado.setHeight("-1px");
		horizontalLayout_2.addComponent(cmbIcmsCustomizado);
		
		// cmbGrupoTributario
		cmbGrupoTributario = new ManyToOneCombo<>();
		cmbGrupoTributario.setCaption("Grupo Tributário");
		cmbGrupoTributario.setImmediate(false);
		cmbGrupoTributario.setWidth("234px");
		cmbGrupoTributario.setHeight("-1px");
		horizontalLayout_2.addComponent(cmbGrupoTributario);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		absoluteLayout_2.addComponent(tabSheet_1, "top:-3.0px;left:20.0px;");
		
		return absoluteLayout_2;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		// absoluteLayout_3
		absoluteLayout_3 = buildAbsoluteLayout_3();
		tabSheet_1.addTab(absoluteLayout_3, "Tab", null);
		
		// absoluteLayout_4
		absoluteLayout_4 = buildAbsoluteLayout_4();
		tabSheet_1.addTab(absoluteLayout_4, "Tab", null);
		
		return tabSheet_1;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_3() {
		// common part: create layout
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("100.0%");
		absoluteLayout_3.setHeight("100.0%");
		
		// txtGtin
		txtGtin = new TextField();
		txtGtin.setCaption("GTIN");
		txtGtin.setImmediate(false);
		txtGtin.setWidth("-1px");
		txtGtin.setHeight("-1px");
		absoluteLayout_3.addComponent(txtGtin, "top:14.0px;left:19.0px;");
		
		// txtCodigoInterno
		txtCodigoInterno = new TextField();
		txtCodigoInterno.setCaption("Código Interno");
		txtCodigoInterno.setImmediate(false);
		txtCodigoInterno.setWidth("-1px");
		txtCodigoInterno.setHeight("-1px");
		absoluteLayout_3.addComponent(txtCodigoInterno,
				"top:14.0px;left:179.0px;");
		
		// cmbNcm
		cmbNcm = new ComboBox();
		cmbNcm.setCaption("NCM");
		cmbNcm.setImmediate(false);
		cmbNcm.setWidth("-1px");
		cmbNcm.setHeight("-1px");
		absoluteLayout_3.addComponent(cmbNcm, "top:14.0px;left:339.0px;");
		
		// cmbInativo
		cmbInativo = new ComboBox();
		cmbInativo.setCaption("Inativo?");
		cmbInativo.setImmediate(false);
		cmbInativo.setWidth("-1px");
		cmbInativo.setHeight("-1px");
		absoluteLayout_3.addComponent(cmbInativo, "top:14.0px;left:527.0px;");
		
		// cmbClasse
		cmbClasse = new ComboBox();
		cmbClasse.setCaption("Classe");
		cmbClasse.setImmediate(false);
		cmbClasse.setWidth("220px");
		cmbClasse.setHeight("-1px");
		absoluteLayout_3.addComponent(cmbClasse, "top:14.0px;left:719.0px;");
		
		// txtNome
		txtNome = new TextField();
		txtNome.setCaption("Nome");
		txtNome.setImmediate(false);
		txtNome.setWidth("480px");
		txtNome.setHeight("-1px");
		absoluteLayout_3.addComponent(txtNome, "top:58.0px;left:19.0px;");
		
		// txtDescricaoPdv
		txtDescricaoPdv = new TextField();
		txtDescricaoPdv.setCaption("Descrição PDV");
		txtDescricaoPdv.setImmediate(false);
		txtDescricaoPdv.setWidth("412px");
		txtDescricaoPdv.setHeight("-1px");
		absoluteLayout_3.addComponent(txtDescricaoPdv,
				"top:58.0px;left:527.0px;");
		
		// txtDescricao
		txtDescricao = new TextField();
		txtDescricao.setCaption("Descrição");
		txtDescricao.setImmediate(false);
		txtDescricao.setWidth("920px");
		txtDescricao.setHeight("-1px");
		absoluteLayout_3.addComponent(txtDescricao, "top:98.0px;left:19.0px;");
		
		// txtValorCompra
		txtValorCompra = new TextField();
		txtValorCompra.setCaption("Valor Compra");
		txtValorCompra.setImmediate(false);
		txtValorCompra.setWidth("119px");
		txtValorCompra.setHeight("-1px");
		absoluteLayout_3.addComponent(txtValorCompra,
				"top:140.0px;left:20.0px;");
		
		// txtValorVenda
		txtValorVenda = new TextField();
		txtValorVenda.setCaption("Valor Venda");
		txtValorVenda.setImmediate(false);
		txtValorVenda.setWidth("122px");
		txtValorVenda.setHeight("-1px");
		absoluteLayout_3.addComponent(txtValorVenda,
				"top:140.0px;left:147.0px;");
		
		// txtValorVendaMinimo
		txtValorVendaMinimo = new TextField();
		txtValorVendaMinimo.setCaption("Valor Venda Mínimo");
		txtValorVendaMinimo.setImmediate(false);
		txtValorVendaMinimo.setWidth("137px");
		txtValorVendaMinimo.setHeight("-1px");
		absoluteLayout_3.addComponent(txtValorVendaMinimo,
				"top:140.0px;left:275.0px;");
		
		// txtValorSugerido
		txtValorSugerido = new TextField();
		txtValorSugerido.setCaption("Valor Sugerido");
		txtValorSugerido.setImmediate(false);
		txtValorSugerido.setWidth("126px");
		txtValorSugerido.setHeight("-1px");
		absoluteLayout_3.addComponent(txtValorSugerido,
				"top:140.0px;left:419.0px;");
		
		// txtCustoMedioLiquido
		txtCustoMedioLiquido = new TextField();
		txtCustoMedioLiquido.setCaption("Custo Médio Líquido");
		txtCustoMedioLiquido.setImmediate(false);
		txtCustoMedioLiquido.setWidth("126px");
		txtCustoMedioLiquido.setHeight("-1px");
		absoluteLayout_3.addComponent(txtCustoMedioLiquido,
				"top:141.0px;left:551.0px;");
		
		// txtPrecoLucroZero
		txtPrecoLucroZero = new TextField();
		txtPrecoLucroZero.setCaption("Preço Lucro Zero");
		txtPrecoLucroZero.setImmediate(false);
		txtPrecoLucroZero.setWidth("126px");
		txtPrecoLucroZero.setHeight("-1px");
		absoluteLayout_3.addComponent(txtPrecoLucroZero,
				"top:141.0px;left:685.0px;");
		
		// txtPrecoLucroMinimo
		txtPrecoLucroMinimo = new TextField();
		txtPrecoLucroMinimo.setCaption("Preço Lucro Mínimo");
		txtPrecoLucroMinimo.setImmediate(false);
		txtPrecoLucroMinimo.setWidth("121px");
		txtPrecoLucroMinimo.setHeight("-1px");
		absoluteLayout_3.addComponent(txtPrecoLucroMinimo,
				"top:141.0px;left:818.0px;");
		
		// txtPrecoLucroMaximo
		txtPrecoLucroMaximo = new TextField();
		txtPrecoLucroMaximo.setCaption("Preço Lucro Máximo");
		txtPrecoLucroMaximo.setImmediate(false);
		txtPrecoLucroMaximo.setWidth("120px");
		txtPrecoLucroMaximo.setHeight("-1px");
		absoluteLayout_3.addComponent(txtPrecoLucroMaximo,
				"top:181.0px;left:19.0px;");
		
		// txtMarkup
		txtMarkup = new TextField();
		txtMarkup.setCaption("Markup");
		txtMarkup.setImmediate(false);
		txtMarkup.setWidth("121px");
		txtMarkup.setHeight("-1px");
		absoluteLayout_3.addComponent(txtMarkup, "top:181.0px;left:148.0px;");
		
		// txtQuantidadeEstoque
		txtQuantidadeEstoque = new TextField();
		txtQuantidadeEstoque.setCaption("Quantidade Estoque");
		txtQuantidadeEstoque.setImmediate(false);
		txtQuantidadeEstoque.setWidth("136px");
		txtQuantidadeEstoque.setHeight("-1px");
		absoluteLayout_3.addComponent(txtQuantidadeEstoque,
				"top:181.0px;left:276.0px;");
		
		// txtQtde
		txtQtde = new TextField();
		txtQtde.setCaption("Qtde Estoque Anterior");
		txtQtde.setImmediate(false);
		txtQtde.setWidth("126px");
		txtQtde.setHeight("-1px");
		absoluteLayout_3.addComponent(txtQtde, "top:181.0px;left:419.0px;");
		
		// txtEstoqueIdeal
		txtEstoqueIdeal = new TextField();
		txtEstoqueIdeal.setCaption("Estoque Ideal");
		txtEstoqueIdeal.setImmediate(false);
		txtEstoqueIdeal.setWidth("128px");
		txtEstoqueIdeal.setHeight("-1px");
		absoluteLayout_3.addComponent(txtEstoqueIdeal,
				"top:182.0px;left:551.0px;");
		
		// txtEstoqueMinimo
		txtEstoqueMinimo = new TextField();
		txtEstoqueMinimo.setCaption("Estoque Mínimo");
		txtEstoqueMinimo.setImmediate(false);
		txtEstoqueMinimo.setWidth("132px");
		txtEstoqueMinimo.setHeight("-1px");
		absoluteLayout_3.addComponent(txtEstoqueMinimo,
				"top:181.0px;left:686.0px;");
		
		// txtEstoqueMaximo
		txtEstoqueMaximo = new TextField();
		txtEstoqueMaximo.setCaption("Estoque Máximo");
		txtEstoqueMaximo.setImmediate(false);
		txtEstoqueMaximo.setWidth("114px");
		txtEstoqueMaximo.setHeight("-1px");
		absoluteLayout_3.addComponent(txtEstoqueMaximo,
				"top:181.0px;left:825.0px;");
		
		return absoluteLayout_3;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_4() {
		// common part: create layout
		absoluteLayout_4 = new AbsoluteLayout();
		absoluteLayout_4.setImmediate(false);
		absoluteLayout_4.setWidth("100.0%");
		absoluteLayout_4.setHeight("100.0%");
		
		// imgProduto
		imgProduto = new ImageViewer();
		imgProduto.setCaption("Imagem do Produto");
		imgProduto.setImmediate(false);
		imgProduto.setWidth("-1px");
		imgProduto.setHeight("130px");
		absoluteLayout_4.addComponent(imgProduto, "top:12.0px;left:9.0px;");
		
		// txtLst
		txtLst = new TextField();
		txtLst.setCaption("LST");
		txtLst.setImmediate(false);
		txtLst.setWidth("40px");
		txtLst.setHeight("-1px");
		absoluteLayout_4.addComponent(txtLst, "top:12.0px;left:159.0px;");
		
		// txtExtipi
		txtExtipi = new TextField();
		txtExtipi.setCaption("EXTIPI");
		txtExtipi.setImmediate(false);
		txtExtipi.setWidth("-1px");
		txtExtipi.setHeight("-1px");
		absoluteLayout_4.addComponent(txtExtipi, "top:12.0px;left:219.0px;");
		
		// cmbTipo
		cmbTipo = new ComboBox();
		cmbTipo.setCaption("Tipo");
		cmbTipo.setImmediate(false);
		cmbTipo.setWidth("80px");
		cmbTipo.setHeight("-1px");
		absoluteLayout_4.addComponent(cmbTipo, "top:12.0px;left:379.0px;");
		
		// cmbIat
		cmbIat = new ComboBox();
		cmbIat.setCaption("IAT");
		cmbIat.setImmediate(false);
		cmbIat.setWidth("100.0%");
		cmbIat.setHeight("-1px");
		absoluteLayout_4.addComponent(cmbIat,
				"top:12.0px;right:426.0px;left:479.0px;");
		
		// cmbIppt
		cmbIppt = new ComboBox();
		cmbIppt.setCaption("IPPT");
		cmbIppt.setImmediate(false);
		cmbIppt.setWidth("106px");
		cmbIppt.setHeight("-1px");
		absoluteLayout_4.addComponent(cmbIppt, "top:12.0px;left:599.0px;");
		
		// cmbTipoItemSped
		cmbTipoItemSped = new ComboBox();
		cmbTipoItemSped.setCaption("Tipo Item Sped");
		cmbTipoItemSped.setImmediate(false);
		cmbTipoItemSped.setWidth("-1px");
		cmbTipoItemSped.setHeight("-1px");
		absoluteLayout_4.addComponent(cmbTipoItemSped,
				"top:12.0px;left:726.0px;");
		
		// txtTotalizadorParcial
		txtTotalizadorParcial = new TextField();
		txtTotalizadorParcial.setCaption("Totalizador Parcial");
		txtTotalizadorParcial.setImmediate(false);
		txtTotalizadorParcial.setWidth("-1px");
		txtTotalizadorParcial.setHeight("-1px");
		absoluteLayout_4.addComponent(txtTotalizadorParcial,
				"top:54.0px;left:158.0px;");
		
		// txtCodigoBalanca
		txtCodigoBalanca = new TextField();
		txtCodigoBalanca.setCaption("Código Balança");
		txtCodigoBalanca.setImmediate(false);
		txtCodigoBalanca.setWidth("-1px");
		txtCodigoBalanca.setHeight("-1px");
		absoluteLayout_4.addComponent(txtCodigoBalanca,
				"top:54.0px;left:319.0px;");
		
		// txtPeso
		txtPeso = new TextField();
		txtPeso.setCaption("Peso");
		txtPeso.setImmediate(false);
		txtPeso.setWidth("140px");
		txtPeso.setHeight("-1px");
		absoluteLayout_4.addComponent(txtPeso, "top:98.0px;left:159.0px;");
		
		// txtTaxaComissao
		txtTaxaComissao = new TextField();
		txtTaxaComissao.setCaption("Taxa Comissão");
		txtTaxaComissao.setImmediate(false);
		txtTaxaComissao.setWidth("-1px");
		txtTaxaComissao.setHeight("-1px");
		absoluteLayout_4.addComponent(txtTaxaComissao,
				"top:98.0px;left:319.0px;");
		
		// txtPontoPedido
		txtPontoPedido = new TextField();
		txtPontoPedido.setCaption("Ponto Pedido");
		txtPontoPedido.setImmediate(false);
		txtPontoPedido.setWidth("-1px");
		txtPontoPedido.setHeight("-1px");
		absoluteLayout_4.addComponent(txtPontoPedido,
				"top:98.0px;left:479.0px;");
		
		// txtLoteEconomicoCompra
		txtLoteEconomicoCompra = new TextField();
		txtLoteEconomicoCompra.setCaption("Lote Econômico Compra");
		txtLoteEconomicoCompra.setImmediate(false);
		txtLoteEconomicoCompra.setWidth("-1px");
		txtLoteEconomicoCompra.setHeight("-1px");
		absoluteLayout_4.addComponent(txtLoteEconomicoCompra,
				"top:98.0px;left:639.0px;");
		
		// txtAliquotaIssqn
		txtAliquotaIssqn = new TextField();
		txtAliquotaIssqn.setCaption("Alíquota ISSQN");
		txtAliquotaIssqn.setImmediate(false);
		txtAliquotaIssqn.setWidth("-1px");
		txtAliquotaIssqn.setHeight("-1px");
		absoluteLayout_4.addComponent(txtAliquotaIssqn,
				"top:139.0px;left:319.0px;");
		
		// txtAliquotaICms
		txtAliquotaICms = new TextField();
		txtAliquotaICms.setCaption("Alíquota ICMS");
		txtAliquotaICms.setImmediate(false);
		txtAliquotaICms.setWidth("-1px");
		txtAliquotaICms.setHeight("-1px");
		absoluteLayout_4.addComponent(txtAliquotaICms,
				"top:137.0px;left:158.0px;");
		
		return absoluteLayout_4;
	}

	public ManyToOneCombo<UnidadeProduto> getCmbUnidadeProduto() {
		return cmbUnidadeProduto;
	}

	public void setCmbUnidadeProduto(
			ManyToOneCombo<UnidadeProduto> cmbUnidadeProduto) {
		this.cmbUnidadeProduto = cmbUnidadeProduto;
	}

	public ManyToOneCombo<MarcaProduto> getCmbMarcaProduto() {
		return cmbMarcaProduto;
	}

	public void setCmbMarcaProduto(ManyToOneCombo<MarcaProduto> cmbMarcaProduto) {
		this.cmbMarcaProduto = cmbMarcaProduto;
	}

	public ManyToOneCombo<Almoxarifado> getCmbAlmoxarifado() {
		return cmbAlmoxarifado;
	}

	public void setCmbAlmoxarifado(ManyToOneCombo<Almoxarifado> cmbAlmoxarifado) {
		this.cmbAlmoxarifado = cmbAlmoxarifado;
	}

	public ManyToOneCombo<GrupoTributario> getCmbGrupoTributario() {
		return cmbGrupoTributario;
	}

	public void setCmbGrupoTributario(
			ManyToOneCombo<GrupoTributario> cmbGrupoTributario) {
		this.cmbGrupoTributario = cmbGrupoTributario;
	}

	public ManyToOneCombo<SubGrupoProduto> getCmbSubGrupoProduto() {
		return cmbSubGrupoProduto;
	}

	public void setCmbSubGrupoProduto(
			ManyToOneCombo<SubGrupoProduto> cmbSubGrupoProduto) {
		this.cmbSubGrupoProduto = cmbSubGrupoProduto;
	}
	
}
