package dc.visao.tributario;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

import dc.control.enums.OrigemMercadoriaEn;
import dc.controller.tributario.IcmsCustomizadoFormController;
import dc.visao.framework.util.ComponentUtil;

public class ICMSCustomizadoFormView extends CustomComponent {

	private static final long serialVersionUID = 1L;
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private GridLayout glGeral;
	
	@AutoGenerated
	private ComboBox cmbOrigemMercadoria;
	@AutoGenerated
	private TextArea txaDescricao;
	
	IcmsCustomizadoFormController controller;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ICMSCustomizadoFormView(IcmsCustomizadoFormController controller) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.controller = controller;
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		glGeral = bglGeral();
		mainLayout.addComponent(glGeral);
		
		for (OrigemMercadoriaEn en : OrigemMercadoriaEn.values()) {
			cmbOrigemMercadoria.addItem(en);
		}
	}

	/**
	 * GERAL
	 */

	@AutoGenerated
	private GridLayout bglGeral() {
		// common part: create layout
		glGeral = new GridLayout(3, 3);
		glGeral.setImmediate(false);
		glGeral.setWidth("100.0%");
		glGeral.setHeight("-1px");
		glGeral.setMargin(false);
		glGeral.setSpacing(true);
		glGeral.setRows(3);
		glGeral.setColumns(3);
		
		// cmbOrigemMercadoria
		cmbOrigemMercadoria = ComponentUtil.buildComboBox("Origem de Mercadoria");
		cmbOrigemMercadoria.setImmediate(true);
		cmbOrigemMercadoria.setHeight("-1px");
		glGeral.addComponent(cmbOrigemMercadoria, 0, 0);
		
		txaDescricao = ComponentUtil.buildTextArea("Descrição");
		txaDescricao.setImmediate(true);
		txaDescricao.setHeight("-1px");
		glGeral.addComponent(txaDescricao, 0, 1);
		
		return glGeral;
		
	}
	
	public VerticalLayout getMainLayout() {
		return mainLayout;
	}

	public void setMainLayout(VerticalLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

	public GridLayout getGlGeral() {
		return glGeral;
	}

	public void setGlGeral(GridLayout glGeral) {
		this.glGeral = glGeral;
	}

	public ComboBox getCmbOrigemMercadoria() {
		return cmbOrigemMercadoria;
	}

	public void setCmbOrigemMercadoria(ComboBox cmbOrigemMercadoria) {
		this.cmbOrigemMercadoria = cmbOrigemMercadoria;
	}

	public TextArea getTxaDescricao() {
		return txaDescricao;
	}

	public void setTxaDescricao(TextArea txaDescricao) {
		this.txaDescricao = txaDescricao;
	}
	
}
