package dc.visao.financeiro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.financeiro.IndiceEconomicoFormController;
import dc.visao.framework.util.ComponentUtil;

public class IndiceEconomicoFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TextArea txtDescricao;
	@AutoGenerated
	private TextField txtNome;
	@AutoGenerated
	private TextField txtSigla;
	
	IndiceEconomicoFormController controller;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public IndiceEconomicoFormView(IndiceEconomicoFormController controller) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.controller = controller;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// txtSigla
		txtSigla = ComponentUtil.buildTextField("Sigla");
		txtSigla.setImmediate(false);
		mainLayout.addComponent(txtSigla);

		// txtNome
		txtNome = ComponentUtil.buildTextField("Nome");
		txtNome.setImmediate(false);
		mainLayout.addComponent(txtNome);

		// txtDescricao
		txtDescricao = ComponentUtil.buildTextArea("Descrição");
		txtDescricao.setImmediate(false);
		mainLayout.addComponent(txtDescricao);

		return mainLayout;
	}

	public TextArea getTxtDescricao() {
		return txtDescricao;
	}

	public void setTxtDescricao(TextArea txtDescricao) {
		this.txtDescricao = txtDescricao;
	}

	public TextField getTxtNome() {
		return txtNome;
	}

	public void setTxtNome(TextField txtNome) {
		this.txtNome = txtNome;
	}

	public TextField getTxtSigla() {
		return txtSigla;
	}

	public void setTxtSigla(TextField txtSigla) {
		this.txtSigla = txtSigla;
	}

}