package dc.visao.financeiro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;

import dc.visao.framework.util.ComponentUtil;

/**
*
* @author Wesley Jr
/*
 * Nessa classe temos a Tela (DESIGN), onde criamos o campos que a Tela cont�m
 * tudo que ela precisa ter
 *
*/

@SuppressWarnings("serial")
public class PlanoCentroResultadoFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private PopupDateField dtDataInclusao;
	@AutoGenerated
	private TextField txtNiveis;
	@AutoGenerated
	private TextField txtMascara;
	@AutoGenerated
	private TextField txtNome;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PlanoCentroResultadoFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}

	public PopupDateField getDtDataInclusao() {
		return dtDataInclusao;
	}

	public void setDtDataInclusao(PopupDateField dtDataInclusao) {
		this.dtDataInclusao = dtDataInclusao;
	}

	public TextField getTxtNiveis() {
		return txtNiveis;
	}

	public void setTxtNiveis(TextField txtNiveis) {
		this.txtNiveis = txtNiveis;
	}

	public TextField getTxtMascara() {
		return txtMascara;
	}

	public void setTxtMascara(TextField txtMascara) {
		this.txtMascara = txtMascara;
	}

	public TextField getTxtNome() {
		return txtNome;
	}

	public void setTxtNome(TextField txtNome) {
		this.txtNome = txtNome;
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		mainLayout.setRows(2);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		

		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		// txtNome
		txtNome = ComponentUtil.buildTextField("Nome");
		txtNome.setWidth("-1px");
		txtNome.setHeight("-1px");
		horizontalLayout_1.addComponent(txtNome);
		
		// txtMascara
		txtMascara = ComponentUtil.buildTextField("Máscara");
		txtMascara.setWidth("-1px");
		txtMascara.setHeight("-1px");
		horizontalLayout_1.addComponent(txtMascara);
		
		//add horizontal_1
		mainLayout.addComponent(horizontalLayout_1,0,0);
		
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("100.0%");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// txtNiveis
		txtNiveis = ComponentUtil.buildNumberField("Níveis");
		txtNiveis.setWidth("-1px");
		txtNiveis.setHeight("-1px");
		horizontalLayout_2.addComponent(txtNiveis);
		
		// dtDataInclusao
		dtDataInclusao = new PopupDateField();
		dtDataInclusao.setCaption("Data Inclusão");
		dtDataInclusao.setImmediate(false);
		dtDataInclusao.setWidth("-1px");
		dtDataInclusao.setHeight("-1px");
		horizontalLayout_2.addComponent(dtDataInclusao);
		
		//add horizontal_2
		mainLayout.addComponent(horizontalLayout_2,0,1);
		
		return mainLayout;
	}
	
}
