package dc.visao.sistema;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextField;

import dc.entidade.framework.SeguimentoEntity;
import dc.visao.framework.util.ComponentUtil;

public class SeguimentoFormView extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private GridLayout mainLayout;

	private TextField txNome;
	private TextField txDescricao;

	public SeguimentoFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		mainLayout.setRows(6);
		mainLayout.setColumns(1);

		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");

		txNome = ComponentUtil.buildTextField("Nome");
		mainLayout.addComponent(txNome, 0, 0);

		txDescricao = ComponentUtil.buildTextField("Descrição");
		mainLayout.addComponent(txDescricao, 0, 1);

		return mainLayout;
	}

	public void preencheBean(SeguimentoEntity currentBean) {
		currentBean.setNome(txNome.getValue());
		currentBean.setDescricao(txDescricao.getValue());

	}

	public void preencheForm(SeguimentoEntity currentBean) {
		txNome.setValue(currentBean.getNome());
		txDescricao.setValue(currentBean.getDescricao());

	}

	public TextField getTxNome() {
		return txNome;
	}

	public void setTxNome(TextField txNome) {
		this.txNome = txNome;
	}

	public TextField getTxDescricao() {
		return txDescricao;
	}

	public void setTxDescricao(TextField txDescricao) {
		this.txDescricao = txDescricao;
	}

}