package dc.visao.suprimento.estoque;

import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Field;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TableFieldFactory;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.suprimento.estoque.LoteProdutoFormController;
import dc.entidade.nfe.NfeDetalheEntity;
import dc.visao.framework.component.SubFormComponent;
import dc.visao.framework.util.ComponentUtil;

public class LoteProdutoFormView extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private GridLayout fields;
	@AutoGenerated
	private TabSheet tabSheet;
	@AutoGenerated
	private VerticalLayout vlProduto;
	@AutoGenerated
	private Panel plProduto;
	
	private TextField txtCodigo, txtNome;
	private TextArea txaDescricao, txaObservacao;
	private PopupDateField pdDataCadastro, pdDataCompra, pdDataFabricacao, pdDataVencimento;
	
	private SubFormComponent<NfeDetalheEntity, Integer> nfeDetalheSubForm = null;
	
	LoteProdutoFormController controller;
	

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoteProdutoFormView(LoteProdutoFormController controller) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.controller = controller;
	}

	private VerticalLayout buildMainLayout() {

		// common part: create layout
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setWidth("100.0%");
		mainLayout.setHeight("100.0%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		fields = buildFields();
		mainLayout.addComponent(fields);
		
		
		tabSheet = new TabSheet();
		tabSheet.setImmediate(true);
		tabSheet.setSizeFull();

		tabSheet.addTab(bvlProduto(), 0);

		mainLayout.addComponent(tabSheet);
		mainLayout.setExpandRatio(tabSheet, 1);
				
		return mainLayout;
	}
	
	private GridLayout buildFields() {
		fields = new GridLayout(6,5);
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		fields.setRows(5);
		fields.setColumns(6);
		
		txtCodigo = ComponentUtil.buildTextField("Código");
		fields.addComponent(txtCodigo, 0, 0);
		
		txtNome = ComponentUtil.buildTextField("Nome");
		fields.addComponent(txtNome, 1, 0);
		
		pdDataCadastro = ComponentUtil.buildPopupDateField("Data Cadastro");
		fields.addComponent(pdDataCadastro, 0, 1);
		
		pdDataCompra = ComponentUtil.buildPopupDateField("Data Compra");
		fields.addComponent(pdDataCompra, 1, 1);
		
		pdDataFabricacao = ComponentUtil.buildPopupDateField("Data Fabricação");
		fields.addComponent(pdDataFabricacao, 2, 1);
		
		pdDataVencimento = ComponentUtil.buildPopupDateField("Data Vencimento");
		fields.addComponent(pdDataVencimento, 3, 1);
		
		txaDescricao = ComponentUtil.buildTextArea("Descrição");
		fields.addComponent(txaDescricao, 0, 2, 1,2);
		
		txaObservacao = ComponentUtil.buildTextArea("Observação");
		fields.addComponent(txaObservacao, 2, 2, 3,2);
		
		return fields;
		
	}
	
	@AutoGenerated
	private VerticalLayout bvlProduto() {
		// common part: create layout
		vlProduto = new VerticalLayout();
		vlProduto.setImmediate(false);
		vlProduto.setWidth("100.0%");
		vlProduto.setHeight("100.0%");
		vlProduto.setMargin(true);
		vlProduto.setSpacing(true);
		vlProduto.setCaption("Produto");

		//
		vlProduto.addComponent(bplProduto());

		return vlProduto;
	}

	@AutoGenerated
	private Panel bplProduto() {
		// common part: create layout
		plProduto = new Panel();
		plProduto.setImmediate(false);
		plProduto.setSizeFull();

		plProduto.setContent(buildNfeDetalheSubForm());

		return plProduto;
	}
	
	@AutoGenerated
	private SubFormComponent<NfeDetalheEntity, Integer> buildNfeDetalheSubForm() {
		nfeDetalheSubForm = new SubFormComponent<NfeDetalheEntity, Integer>(NfeDetalheEntity.class, 
				new String[] { "item", "gtin", "descricao","unidade", "cfop", "quantidade","valorUnitario", "valorTotal" }, 
				new String[] {"Item", "GTIN", "Descrição","Unidade", "CFOP", "Quantidade", "Valor Unitário","Valor Total" }) {


			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			protected TableFieldFactory getFieldFactory() {
				return new TableFieldFactory() {

					/**
					 * 
					 */
					private static final long serialVersionUID = 1L;
					@Override
					public Field<?> createField(Container container,
							Object itemId, Object propertyId,
							Component uiContext) {
						if ("item".equals(propertyId)) {
							TextField field = ComponentUtil.buildNumericField(null);
							return field;
						} else if ("gtin".equals(propertyId)) {
							TextField textField = ComponentUtil.buildTextField(null);
							return textField;
						} else if ("descricao".equals(propertyId)) {
							TextField textField = ComponentUtil.buildTextField(null);
							return textField;
						} else if ("unidade".equals(propertyId)) {
							TextField textField = ComponentUtil.buildTextField(null);
							return textField;
						} else if ("cfop".equals(propertyId)) {
							TextField textField = ComponentUtil.buildNumericField(null);
							return textField;
						} else if ("quantidade".equals(propertyId)) {
							TextField textField = ComponentUtil.buildCurrencyField(null);
							return textField;
						} else if ("valorUnitario".equals(propertyId)) {
							TextField textField = ComponentUtil.buildCurrencyField(null);
							return textField;
						} else if ("valorTotal".equals(propertyId)) {
							TextField textField = ComponentUtil.buildCurrencyField(null);
							return textField;
						}
						
						else {
							return ComponentUtil.buildTextField(null);
						}
					}

				};
			}
			
			protected NfeDetalheEntity getNovo() {
				NfeDetalheEntity nfe = controller
						.novoNfe();
				return nfe;
			}

			protected void getRemoverSelecionados(
					List<NfeDetalheEntity> values) {
				controller.removerNfe(values);
			}

			@Override
			public boolean validateItems(List<NfeDetalheEntity> items) {
				return true;
			}
		};

		return nfeDetalheSubForm;
		
	}
	
	public void preencheSubForm(List<NfeDetalheEntity> detalhes) {
		nfeDetalheSubForm.fillWith(detalhes);
	}

	public VerticalLayout getMainLayout() {
		return mainLayout;
	}

	public void setMainLayout(VerticalLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

	public GridLayout getFields() {
		return fields;
	}

	public void setFields(GridLayout fields) {
		this.fields = fields;
	}

	public TabSheet getTabSheet() {
		return tabSheet;
	}

	public void setTabSheet(TabSheet tabSheet) {
		this.tabSheet = tabSheet;
	}

	public TextField getTxtCodigo() {
		return txtCodigo;
	}

	public void setTxtCodigo(TextField txtCodigo) {
		this.txtCodigo = txtCodigo;
	}

	public TextField getTxtNome() {
		return txtNome;
	}

	public void setTxtNome(TextField txtNome) {
		this.txtNome = txtNome;
	}

	public TextArea getTxaDescricao() {
		return txaDescricao;
	}

	public void setTxaDescricao(TextArea txaDescricao) {
		this.txaDescricao = txaDescricao;
	}

	public TextArea getTxaObservacao() {
		return txaObservacao;
	}

	public void setTxaObservacao(TextArea txaObservacao) {
		this.txaObservacao = txaObservacao;
	}

	public PopupDateField getPdDataCadastro() {
		return pdDataCadastro;
	}

	public void setPdDataCadastro(PopupDateField pdDataCadastro) {
		this.pdDataCadastro = pdDataCadastro;
	}

	public PopupDateField getPdDataCompra() {
		return pdDataCompra;
	}

	public void setPdDataCompra(PopupDateField pdDataCompra) {
		this.pdDataCompra = pdDataCompra;
	}

	public PopupDateField getPdDataFabricacao() {
		return pdDataFabricacao;
	}

	public void setPdDataFabricacao(PopupDateField pdDataFabricacao) {
		this.pdDataFabricacao = pdDataFabricacao;
	}

	public PopupDateField getPdDataVencimento() {
		return pdDataVencimento;
	}

	public void setPdDataVencimento(PopupDateField pdDataVencimento) {
		this.pdDataVencimento = pdDataVencimento;
	}

	public SubFormComponent<NfeDetalheEntity, Integer> getNfeDetalheSubForm() {
		return nfeDetalheSubForm;
	}

	public void setNfeDetalheSubForm(
			SubFormComponent<NfeDetalheEntity, Integer> nfeDetalheSubForm) {
		this.nfeDetalheSubForm = nfeDetalheSubForm;
	}

	public LoteProdutoFormController getController() {
		return controller;
	}

	public void setController(LoteProdutoFormController controller) {
		this.controller = controller;
	}
	
}
