package dc.visao.geral;

import java.math.BigDecimal;
import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.control.enums.LocalizacaoEn;
import dc.control.enums.SimNaoEn;
import dc.controller.geral.pessoal.FornecedorFormController;
import dc.entidade.geral.pessoal.AtividadeForCliEntity;
import dc.entidade.geral.pessoal.FornecedorEntity;
import dc.entidade.geral.pessoal.PessoaEntity;
import dc.entidade.geral.pessoal.SituacaoForCliEntity;
import dc.visao.framework.component.BigDecimalConverter;
import dc.visao.framework.component.IntegerConverter;
import dc.visao.framework.component.manytoonecombo.ManyToOneComboField;
import dc.visao.framework.util.ComponentUtil;

public class FornecedorFormView extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private ManyToOneComboField<PessoaEntity> mocPessoa;

	@AutoGenerated
	private ManyToOneComboField<SituacaoForCliEntity> mocSituacaoForCli;

	@AutoGenerated
	private ManyToOneComboField<AtividadeForCliEntity> mocAtividadeForCli;

	@AutoGenerated
	private PopupDateField pdfDesde;

	@AutoGenerated
	private TextField tfContaRemetente;

	@AutoGenerated
	private ComboBox cbGerarFaturamento;

	@AutoGenerated
	private ComboBox cbOptanteSimples;

	@AutoGenerated
	private ComboBox cbLocalizacao;

	@AutoGenerated
	private ComboBox cbSofreRentencao;

	@AutoGenerated
	private TextField tfPrazoMedioEntrega;

	@AutoGenerated
	private TextField tfNumDiasPrimeiroVenc;

	@AutoGenerated
	private TextField tfNumDiasIntervalo;

	@AutoGenerated
	private TextField tfQuantidadesParcelas;

	@AutoGenerated
	private TextField tfChequeNominalA;

	@AutoGenerated
	private TextArea taObservacao;
	
	@AutoGenerated
	private GridLayout gridLayout_1;

	private FornecedorFormController controller;

	public FornecedorFormView(FornecedorFormController controller) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.controller = controller;
	}

	public ManyToOneComboField<PessoaEntity> getMocPessoa() {
		return mocPessoa;
	}

	public void setMocPessoa(ManyToOneComboField<PessoaEntity> mocPessoa) {
		this.mocPessoa = mocPessoa;
	}

	public ManyToOneComboField<SituacaoForCliEntity> getMocSituacaoForCli() {
		return mocSituacaoForCli;
	}

	public void setMocSituacaoForCli(
			ManyToOneComboField<SituacaoForCliEntity> mocSituacaoForCli) {
		this.mocSituacaoForCli = mocSituacaoForCli;
	}

	public ManyToOneComboField<AtividadeForCliEntity> getMocAtividadeForCli() {
		return mocAtividadeForCli;
	}

	public void setMocAtividadeForCli(
			ManyToOneComboField<AtividadeForCliEntity> mocAtividadeForCli) {
		this.mocAtividadeForCli = mocAtividadeForCli;
	}

	public PopupDateField getPdfDesde() {
		return pdfDesde;
	}

	public void setPdfDesde(PopupDateField pdfDesde) {
		this.pdfDesde = pdfDesde;
	}

	public TextField getTfContaRemetente() {
		return tfContaRemetente;
	}

	public void setTfContaRemetente(TextField tfContaRemetente) {
		this.tfContaRemetente = tfContaRemetente;
	}

	public ComboBox getCbGerarFaturamento() {
		return cbGerarFaturamento;
	}

	public void setCbGerarFaturamento(ComboBox cbGerarFaturamento) {
		this.cbGerarFaturamento = cbGerarFaturamento;
	}

	public ComboBox getCbOptanteSimples() {
		return cbOptanteSimples;
	}

	public void setCbOptanteSimples(ComboBox cbOptanteSimples) {
		this.cbOptanteSimples = cbOptanteSimples;
	}

	public ComboBox getCbLocalizacao() {
		return cbLocalizacao;
	}

	public void setCbLocalizacao(ComboBox cbLocalizacao) {
		this.cbLocalizacao = cbLocalizacao;
	}

	public ComboBox getCbSofreRentencao() {
		return cbSofreRentencao;
	}

	public void setCbSofreRentencao(ComboBox cbSofreRentencao) {
		this.cbSofreRentencao = cbSofreRentencao;
	}

	public TextField getTfPrazoMedioEntrega() {
		return tfPrazoMedioEntrega;
	}

	public void setTfPrazoMedioEntrega(TextField tfPrazoMedioEntrega) {
		this.tfPrazoMedioEntrega = tfPrazoMedioEntrega;
	}

	public TextField getTfNumDiasPrimeiroVenc() {
		return tfNumDiasPrimeiroVenc;
	}

	public void setTfNumDiasPrimeiroVenc(TextField tfNumDiasPrimeiroVenc) {
		this.tfNumDiasPrimeiroVenc = tfNumDiasPrimeiroVenc;
	}

	public TextField getTfNumDiasIntervalo() {
		return tfNumDiasIntervalo;
	}

	public void setTfNumDiasIntervalo(TextField tfNumDiasIntervalo) {
		this.tfNumDiasIntervalo = tfNumDiasIntervalo;
	}

	public TextField getTfQuantidadesParcelas() {
		return tfQuantidadesParcelas;
	}

	public void setTfQuantidadesParcelas(TextField tfQuantidadesParcelas) {
		this.tfQuantidadesParcelas = tfQuantidadesParcelas;
	}

	public TextField getTfChequeNominalA() {
		return tfChequeNominalA;
	}

	public void setTfChequeNominalA(TextField tfChequeNominalA) {
		this.tfChequeNominalA = tfChequeNominalA;
	}

	public TextArea getTaObservacao() {
		return taObservacao;
	}

	public void setTaObservacao(TextArea taObservacao) {
		this.taObservacao = taObservacao;
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		setWidth("100.0%");
	
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1);
		
		for (SimNaoEn value : SimNaoEn.values()) {
			getCbSofreRentencao().addItem(value);
			getCbGerarFaturamento().addItem(value);
			getCbOptanteSimples().addItem(value);
		}

		for (LocalizacaoEn value : LocalizacaoEn.values()) {
			getCbLocalizacao().addItem(value);
		}
		
		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {

		gridLayout_1 = new GridLayout(7, 7);
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setMargin(true);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setRows(7);
		gridLayout_1.setColumns(7);

		mocPessoa = new ManyToOneComboField<>(PessoaEntity.class);
		mocPessoa.setCaption("Pessoa");
		gridLayout_1.addComponent(mocPessoa, 0, 0, 3, 0);
		
		mocAtividadeForCli = new ManyToOneComboField<>(AtividadeForCliEntity.class);
		mocAtividadeForCli.setCaption("Atividade");
		gridLayout_1.addComponent(mocAtividadeForCli, 0, 1, 1, 1);	
		

		mocSituacaoForCli = new ManyToOneComboField<>(SituacaoForCliEntity.class);
		mocSituacaoForCli.setCaption("Situação");
		gridLayout_1.addComponent(mocSituacaoForCli, 2, 1, 3, 1);
		

		pdfDesde = ComponentUtil.buildPopupDateField("Desde");
		gridLayout_1.addComponent(pdfDesde, 0, 3);

		tfContaRemetente = ComponentUtil.buildTextField("Conta Remetente");
		gridLayout_1.addComponent(tfContaRemetente, 1, 3);

		cbGerarFaturamento = ComponentUtil.buildComboBox("Gerar Faturamento");
		gridLayout_1.addComponent(cbGerarFaturamento, 2, 3);

		cbOptanteSimples = ComponentUtil.buildComboBox("Optante Simples");
		gridLayout_1.addComponent(cbOptanteSimples, 3, 3);

		cbLocalizacao = ComponentUtil.buildComboBox("Localização");
		gridLayout_1.addComponent(cbLocalizacao, 4, 3);

		cbSofreRentencao = ComponentUtil.buildComboBox("Sofre Retenção");
		gridLayout_1.addComponent(cbSofreRentencao, 5, 3);
		//
		tfPrazoMedioEntrega = ComponentUtil
				.buildNumericField("Prazo Médio Entrega");
		tfPrazoMedioEntrega.setConverter(new BigDecimalConverter());
		gridLayout_1.addComponent(tfPrazoMedioEntrega, 0, 4);

		tfNumDiasPrimeiroVenc = ComponentUtil
				.buildNumericField("Núm. Dias 1º Vencimento");
		tfNumDiasPrimeiroVenc.setConverter(new IntegerConverter());
		gridLayout_1.addComponent(tfNumDiasPrimeiroVenc, 1, 4);

		tfNumDiasIntervalo = ComponentUtil
				.buildNumericField("Núm. Dias Intervalo");
		tfNumDiasIntervalo.setConverter(new IntegerConverter());
		gridLayout_1.addComponent(tfNumDiasIntervalo, 2, 4);

		tfQuantidadesParcelas = ComponentUtil
				.buildNumericField("Quantidade Parcelas");
		tfQuantidadesParcelas.setConverter(new IntegerConverter());
		gridLayout_1.addComponent(tfQuantidadesParcelas, 3, 4);

		tfChequeNominalA = ComponentUtil.buildTextField("Cheque Nominal à");
		gridLayout_1.addComponent(tfChequeNominalA, 4, 4, 5, 4);

		taObservacao = ComponentUtil.buildTextArea("Observação");
		gridLayout_1.addComponent(taObservacao, 0, 5, 5, 5);

		return gridLayout_1;
	}

	public void preencheBean(FornecedorEntity currentBean) {
		currentBean.setAtividadeForCli(mocAtividadeForCli.getValue());
		currentBean.setChequeNominalA(tfChequeNominalA.getValue());
		currentBean.setContaRemetente(tfContaRemetente.getValue());
		currentBean.setDesde(pdfDesde.getValue());
		currentBean.setNumDiasIntervalo((Integer) tfNumDiasIntervalo
				.getConvertedValue());
		currentBean
				.setNumDiasPrimeiroVencimento((Integer) tfNumDiasPrimeiroVenc
						.getConvertedValue());
		currentBean.setObservacao(taObservacao.getValue());
		// currentBean.setOptanteSimplesNacional(((SimNaoEn) cbOptanteSimples
		// .getValue()).getCodigo());
		currentBean.setPessoa(mocPessoa.getValue());
		currentBean.setPrazoMedioEntrega((BigDecimal) tfPrazoMedioEntrega
				.getConvertedValue());
		currentBean.setQuantidadeParcelas((Integer) tfQuantidadesParcelas
				.getConvertedValue());
		currentBean.setSituacaoForCli(mocSituacaoForCli.getValue());
		// currentBean.setSofreRetencao(((SimNaoEn) cbOptanteSimples.getValue())
		// .getCodigo());
		// currentBean.setLocalizacao(((Localizacao) cbLocalizacao.getValue())
		// .getCodigo());

		if (currentBean.getDataCadastro() == null) {
			currentBean.setDataCadastro(new Date());
		}
	}

	public void preencheForm(FornecedorEntity currentBean) {
		mocAtividadeForCli.setValue(currentBean.getAtividadeForCli());
		tfChequeNominalA.setValue(currentBean.getChequeNominalA());
		tfContaRemetente.setValue(currentBean.getContaRemetente());
		pdfDesde.setValue(currentBean.getDesde());
		tfNumDiasIntervalo.setConvertedValue(currentBean.getNumDiasIntervalo());
		tfNumDiasPrimeiroVenc.setConvertedValue(currentBean
				.getNumDiasPrimeiroVencimento());
		taObservacao.setValue(currentBean.getObservacao());
		// cbOptanteSimples.setValue(SimNaoEn.getEn(currentBean
		// .getOptanteSimplesNacional()));
		mocPessoa.setValue(currentBean.getPessoa());
		tfPrazoMedioEntrega.setConvertedValue(currentBean
				.getPrazoMedioEntrega());
		tfQuantidadesParcelas.setConvertedValue(currentBean
				.getQuantidadeParcelas());
		mocSituacaoForCli.setValue(currentBean.getSituacaoForCli());
		// cbOptanteSimples
		// .setValue(SimNaoEn.getEn(currentBean.getSofreRetencao()));
		// cbLocalizacao.setValue(Localizacao.getLocalizacao(currentBean
		// .getLocalizacao()));
	}

	public enum Localizacao {

		Nacional("Nacional", "N"), Internacional("Internacional", "I");

		private Localizacao(String label, String codigo) {
			this.label = label;
			this.codigo = codigo;
		}

		private String label;
		private String codigo;

		public static Localizacao getLocalizacao(String codigo) {
			for (Localizacao e : Localizacao.values()) {
				if (e.getCodigo().equalsIgnoreCase(codigo)) {
					return e;
				}
			}

			return null;
		}

		public String getCodigo() {
			return codigo;
		}

		public String getLabel() {
			return label;
		}

		@Override
		public String toString() {
			return label;
		}
	}

}