package dc.visao.diversos;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.entidade.contabilidade.ContabilConta;
import dc.entidade.financeiro.ContaCaixa;
import dc.visao.framework.component.IntegerConverter;
import dc.visao.framework.component.manytoonecombo.ManyToOneCombo;

public class OperadoraCartaoFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private GridLayout fields;
	
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private TextField txtTelefone2;

	@AutoGenerated
	private TextField txtTelefone1;

	@AutoGenerated
	private TextField txtVencimentoAluguel;

	@AutoGenerated
	private TextField txtValorAluguelPosPin;

	@AutoGenerated
	private TextField txtTaxaAdmDebito;

	@AutoGenerated
	private TextField txtTaxaAdm;

	@AutoGenerated
	private TextField txtNome;

	@AutoGenerated
	private TextField txtBandeira;
	
	private ManyToOneCombo<ContaCaixa> cmbContaCaixa;
	private ManyToOneCombo<ContabilConta> cmbContabilConta;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public OperadoraCartaoFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {

		// common part: create layout
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		// setHeight("100.0%");

		fields = buildFields();

		mainLayout.addComponent(fields);
	
		return mainLayout;
	}

	
	private GridLayout buildFields() {
		fields = new GridLayout();
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		fields.setRows(5);
		fields.setColumns(5);

		
		// cmbContaCaixa

		cmbContaCaixa = new ManyToOneCombo<>();
		cmbContaCaixa.setCaption("Conta Caixa");
		cmbContaCaixa.setImmediate(false);
		cmbContaCaixa.setWidth("640px");
		cmbContaCaixa.setHeight("-1px");
		cmbContaCaixa.setSizeFull();
		fields.addComponent(cmbContaCaixa, 0 , 0);
		
		// cmbContabilConta

		cmbContabilConta = new ManyToOneCombo<>();
		cmbContabilConta.setCaption("Contábil Conta");
		cmbContabilConta.setImmediate(false);
		cmbContabilConta.setWidth("640px");
		cmbContabilConta.setHeight("-1px");
		cmbContabilConta.setSizeFull();
		fields.addComponent(cmbContabilConta, 0 , 1);
		
		// txtBandeira
		txtBandeira = new TextField();
		txtBandeira.setCaption("Bandeira");
		txtBandeira.setImmediate(false);
		txtBandeira.setWidth("-1px");
		txtBandeira.setHeight("-1px");
		txtBandeira.setRequired(true);
		txtBandeira.setSizeFull();
		fields.addComponent(txtBandeira, 0 , 2);

		// txtNome
		txtNome = new TextField();
		txtNome.setCaption("Nome");
		txtNome.setImmediate(false);
		txtNome.setWidth("-1px");
		txtNome.setHeight("-1px");
		txtNome.setRequired(true);
		txtNome.setSizeFull();
		fields.addComponent(txtNome, 1, 2);

		// txtTaxaAdm
		txtTaxaAdm = new TextField();
		txtTaxaAdm.setCaption("Taxa ADM");
		txtTaxaAdm.setImmediate(false);
		txtTaxaAdm.setWidth("-1px");
		txtTaxaAdm.setHeight("-1px");
		txtTaxaAdm.setSizeFull();
		fields.addComponent(txtTaxaAdm, 0, 3);

		// txtTaxaAdmDebito
		txtTaxaAdmDebito = new TextField();
		txtTaxaAdmDebito.setCaption("Taxa ADM Débito");
		txtTaxaAdmDebito.setImmediate(false);
		txtTaxaAdmDebito.setWidth("-1px");
		txtTaxaAdmDebito.setHeight("-1px");
		txtTaxaAdmDebito.setSizeFull();
		fields.addComponent(txtTaxaAdmDebito, 1, 3);

		// txtValorAluguelPosPin
		txtValorAluguelPosPin = new TextField();
		txtValorAluguelPosPin.setCaption("Valor Aluguel Pos Pin");
		txtValorAluguelPosPin.setImmediate(false);
		txtValorAluguelPosPin.setWidth("-1px");
		txtValorAluguelPosPin.setHeight("-1px");
		txtValorAluguelPosPin.setSizeFull();
		fields.addComponent(txtValorAluguelPosPin, 2, 3);

		// txtVencimentoAluguel
		txtVencimentoAluguel = new TextField();
		txtVencimentoAluguel.setCaption("Vencimento Aluguel");
		txtVencimentoAluguel.setImmediate(false);
		txtVencimentoAluguel.setWidth("-1px");
		txtVencimentoAluguel.setHeight("-1px");
		txtVencimentoAluguel.setSizeFull();
		txtVencimentoAluguel.setRequired(true);
		txtVencimentoAluguel.setConverter(new IntegerConverter());
		fields.addComponent(txtVencimentoAluguel, 3, 3);

		// txtTelefone1
		txtTelefone1 = new TextField();
		txtTelefone1.setCaption("Telefone 1");
		txtTelefone1.setImmediate(false);
		txtTelefone1.setWidth("-1px");
		txtTelefone1.setHeight("-1px");
		txtTelefone1.setSizeFull();
		fields.addComponent(txtTelefone1, 0, 4);

		// txtTelefone2
		txtTelefone2 = new TextField();
		txtTelefone2.setCaption("Telefone 2");
		txtTelefone2.setImmediate(false);
		txtTelefone2.setWidth("-1px");
		txtTelefone2.setHeight("-1px");
		txtTelefone2.setSizeFull();
		fields.addComponent(txtTelefone2, 1, 4);

		return fields;
	}

	public TextField getTxtTelefone2() {
		return txtTelefone2;
	}

	public void setTxtTelefone2(TextField txtTelefone2) {
		this.txtTelefone2 = txtTelefone2;
	}

	public TextField getTxtTelefone1() {
		return txtTelefone1;
	}

	public void setTxtTelefone1(TextField txtTelefone1) {
		this.txtTelefone1 = txtTelefone1;
	}

	public TextField getTxtVencimentoAluguel() {
		return txtVencimentoAluguel;
	}

	public void setTxtVencimentoAluguel(TextField txtVencimentoAluguel) {
		this.txtVencimentoAluguel = txtVencimentoAluguel;
	}

	public TextField getTxtValorAluguelPosPin() {
		return txtValorAluguelPosPin;
	}

	public void setTxtValorAluguelPosPin(TextField txtValorAluguelPosPin) {
		this.txtValorAluguelPosPin = txtValorAluguelPosPin;
	}

	public TextField getTxtTaxaAdmDebito() {
		return txtTaxaAdmDebito;
	}

	public void setTxtTaxaAdmDebito(TextField txtTaxaAdmDebito) {
		this.txtTaxaAdmDebito = txtTaxaAdmDebito;
	}

	public TextField getTxtTaxaAdm() {
		return txtTaxaAdm;
	}

	public void setTxtTaxaAdm(TextField txtTaxaAdm) {
		this.txtTaxaAdm = txtTaxaAdm;
	}

	public TextField getTxtNome() {
		return txtNome;
	}

	public void setTxtNome(TextField txtNome) {
		this.txtNome = txtNome;
	}

	public TextField getTxtBandeira() {
		return txtBandeira;
	}

	public void setTxtBandeira(TextField txtBandeira) {
		this.txtBandeira = txtBandeira;
	}

	public GridLayout getFields() {
		return fields;
	}

	public void setFields(GridLayout fields) {
		this.fields = fields;
	}

	public VerticalLayout getMainLayout() {
		return mainLayout;
	}

	public void setMainLayout(VerticalLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

	public ManyToOneCombo<ContaCaixa> getCmbContaCaixa() {
		return cmbContaCaixa;
	}

	public void setCmbContaCaixa(ManyToOneCombo<ContaCaixa> cmbContaCaixa) {
		this.cmbContaCaixa = cmbContaCaixa;
	}

	public ManyToOneCombo<ContabilConta> getCmbContabilConta() {
		return cmbContabilConta;
	}

	public void setCmbContabilConta(ManyToOneCombo<ContabilConta> cmbContabilConta) {
		this.cmbContabilConta = cmbContabilConta;
	}
	
}