package dc.visao.geral.outro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.geral.outro.ConvenioFormController;
import dc.entidade.geral.diverso.UfEntity;
import dc.entidade.geral.pessoal.PessoaEntity;
import dc.visao.framework.component.manytoonecombo.ManyToOneCombo;

public class ConvenioFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private GridLayout fields;

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private TextField tfCep;

	@AutoGenerated
	private TextArea tfDescricao;

	@AutoGenerated
	private PopupDateField pdfDataCadastro;

	@AutoGenerated
	private TextField tfTelefone;

	@AutoGenerated
	private TextField tfContato;

	@AutoGenerated
	private ManyToOneCombo<UfEntity> mocUf;

	@AutoGenerated
	private ManyToOneCombo<PessoaEntity> mocPessoa;

	@AutoGenerated
	private TextField tfMunicipioIBGE;

	@AutoGenerated
	private TextField tfBairro;

	@AutoGenerated
	private TextField tfNumero;

	@AutoGenerated
	private TextField tfLogradouro;

	@AutoGenerated
	private PopupDateField pdfDataVencimento;

	@AutoGenerated
	private TextField tfDesconto;

	@AutoGenerated
	private TextField tfNome;

	@AutoGenerated
	private TextField tfCnpj;

	@AutoGenerated
	private TextField tfEmail;

	@AutoGenerated
	private TextField tfSite;

	private ConvenioFormController controller;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public ConvenioFormView(ConvenioFormController controller) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.controller = controller;
	}

	public TextField getTfCep() {
		return tfCep;
	}

	public void setTfCep(TextField tfCep) {
		this.tfCep = tfCep;
	}

	public TextArea getTfDescricao() {
		return tfDescricao;
	}

	public void setTfDescricao(TextArea tfDescricao) {
		this.tfDescricao = tfDescricao;
	}

	public PopupDateField getPdfDataCadastro() {
		return pdfDataCadastro;
	}

	public void setPdfDataCadastro(PopupDateField pdfDataCadastro) {
		this.pdfDataCadastro = pdfDataCadastro;
	}

	public TextField getTfTelefone() {
		return tfTelefone;
	}

	public void setTfTelefone(TextField tfTelefone) {
		this.tfTelefone = tfTelefone;
	}

	public TextField getTfContato() {
		return tfContato;
	}

	public void setTfContato(TextField tfContato) {
		this.tfContato = tfContato;
	}

	public ManyToOneCombo<UfEntity> getMocUf() {
		return mocUf;
	}

	public void setMocUf(ManyToOneCombo<UfEntity> mocUf) {
		this.mocUf = mocUf;
	}

	public ManyToOneCombo<PessoaEntity> getMocPessoa() {
		return mocPessoa;
	}

	public void setMocPessoa(ManyToOneCombo<PessoaEntity> mocPessoa) {
		this.mocPessoa = mocPessoa;
	}

	public TextField getTfMunicipioIBGE() {
		return tfMunicipioIBGE;
	}

	public void setTfMunicipioIBGE(TextField tfMunicipioIBGE) {
		this.tfMunicipioIBGE = tfMunicipioIBGE;
	}

	public TextField getTfBairro() {
		return tfBairro;
	}

	public void setTfBairro(TextField tfBairro) {
		this.tfBairro = tfBairro;
	}

	public TextField getTfNumero() {
		return tfNumero;
	}

	public void setTfNumero(TextField tfNumero) {
		this.tfNumero = tfNumero;
	}

	public TextField getTfLogradouro() {
		return tfLogradouro;
	}

	public void setTfLogradouro(TextField tfLogradouro) {
		this.tfLogradouro = tfLogradouro;
	}

	public PopupDateField getPdfDataVencimento() {
		return pdfDataVencimento;
	}

	public void setPdfDataVencimento(PopupDateField pdfDataVencimento) {
		this.pdfDataVencimento = pdfDataVencimento;
	}

	public TextField getTfDesconto() {
		return tfDesconto;
	}

	public void setTfDesconto(TextField tfDesconto) {
		this.tfDesconto = tfDesconto;
	}

	public TextField getTfNome() {
		return tfNome;
	}

	public void setTfNome(TextField tfNome) {
		this.tfNome = tfNome;
	}

	public TextField getTfCnpj() {
		return tfCnpj;
	}

	public void setTfCnpj(TextField tfCnpj) {
		this.tfCnpj = tfCnpj;
	}

	public TextField getTfEmail() {
		return tfEmail;
	}

	public void setTfEmail(TextField tfEmail) {
		this.tfEmail = tfEmail;
	}

	public TextField getTfSite() {
		return tfSite;
	}

	public void setTfSite(TextField tfSite) {
		this.tfSite = tfSite;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		// setHeight("100.0%");

		fields = buildFields();

		mainLayout.addComponent(fields);

		return mainLayout;
	}

	private GridLayout buildFields() {
		fields = new GridLayout();
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		fields.setRows(7);
		fields.setColumns(7);

		// txtDesconto
		tfDesconto = new TextField();
		tfDesconto.setCaption("Desconto");
		tfDesconto.setImmediate(false);
		tfDesconto.setWidth("-1px");
		tfDesconto.setHeight("-1px");
		tfDesconto.setSizeFull();
		fields.addComponent(tfDesconto, 0, 0);

		// dnDataVencimento
		pdfDataVencimento = new PopupDateField();
		pdfDataVencimento.setCaption("Data Vencimento");
		pdfDataVencimento.setImmediate(false);
		pdfDataVencimento.setWidth("-1px");
		pdfDataVencimento.setHeight("-1px");
		pdfDataVencimento.setSizeFull();
		fields.addComponent(pdfDataVencimento, 1, 0);

		// txtNome
		tfNome = new TextField();
		tfNome.setCaption("Nome");
		tfNome.setImmediate(false);
		tfNome.setRequired(true);
		tfNome.setWidth("800px");
		tfNome.setHeight("-1px");
		tfNome.setSizeFull();
		fields.addComponent(tfNome, 2, 0);

		// txtCnpj
		tfCnpj = new TextField();
		tfCnpj.setCaption("CNPJ");
		tfCnpj.setImmediate(false);
		tfCnpj.setWidth("800px");
		tfCnpj.setHeight("-1px");
		tfCnpj.setSizeFull();
		fields.addComponent(tfCnpj, 3, 0);

		// txtLogradouro
		tfLogradouro = new TextField();
		tfLogradouro.setCaption("Logradouro");
		tfLogradouro.setImmediate(false);
		tfLogradouro.setRequired(true);
		tfLogradouro.setWidth("600px");
		tfLogradouro.setHeight("-1px");
		tfLogradouro.setSizeFull();
		fields.addComponent(tfLogradouro, 0, 1);

		// txtNumero
		tfNumero = new TextField();
		tfNumero.setCaption("Número");
		tfNumero.setImmediate(false);
		tfNumero.setWidth("-1px");
		tfNumero.setHeight("-1px");
		tfNumero.setSizeFull();
		fields.addComponent(tfNumero, 0, 2);

		// txtBairro
		tfBairro = new TextField();
		tfBairro.setCaption("Bairro");
		tfBairro.setImmediate(false);
		tfBairro.setWidth("-1px");
		tfBairro.setHeight("-1px");
		tfBairro.setSizeFull();
		fields.addComponent(tfBairro, 1, 2);

		// txtMunicipioIBGE
		tfMunicipioIBGE = new TextField();
		tfMunicipioIBGE.setCaption("Municipio IBGE");
		tfMunicipioIBGE.setImmediate(false);
		tfMunicipioIBGE.setWidth("-1px");
		tfMunicipioIBGE.setHeight("-1px");
		tfMunicipioIBGE.setSizeFull();
		fields.addComponent(tfMunicipioIBGE, 2, 2);

		// cmbUF
		mocUf = new ManyToOneCombo<>();
		mocUf.setCaption("UF");
		mocUf.setWidth("120px");
		mocUf.setHeight("-1px");
		mocUf.setSizeFull();
		fields.addComponent(mocUf, 0, 3);

		// txtContato
		tfContato = new TextField();
		tfContato.setCaption("Contato");
		tfContato.setImmediate(false);
		tfContato.setWidth("-1px");
		tfContato.setHeight("-1px");
		tfContato.setSizeFull();
		fields.addComponent(tfContato, 1, 3);

		// txtTelefone
		tfTelefone = new TextField();
		tfTelefone.setCaption("Telefone");
		tfTelefone.setImmediate(false);
		tfTelefone.setWidth("-1px");
		tfTelefone.setHeight("-1px");
		tfTelefone.setSizeFull();
		fields.addComponent(tfTelefone, 2, 3);

		// dnDataCadastro
		pdfDataCadastro = new PopupDateField();
		pdfDataCadastro.setCaption("Data Cadastro");
		pdfDataCadastro.setImmediate(false);
		pdfDataCadastro.setWidth("-1px");
		pdfDataCadastro.setHeight("-1px");
		pdfDataCadastro.setSizeFull();
		fields.addComponent(pdfDataCadastro, 3, 3);

		// txtDescricao
		tfDescricao = new TextArea();
		tfDescricao.setCaption("Descrição");
		tfDescricao.setImmediate(false);
		tfDescricao.setWidth("240px");
		tfDescricao.setHeight("-1px");
		tfDescricao.setSizeFull();
		fields.addComponent(tfDescricao, 0, 4);

		// txtCep
		tfCep = new TextField();
		tfCep.setCaption("CEP");
		tfCep.setImmediate(false);
		tfCep.setWidth("-1px");
		tfCep.setHeight("-1px");
		tfCep.setSizeFull();
		fields.addComponent(tfCep, 1, 4);

		// txtEmail
		tfEmail = new TextField();
		tfEmail.setCaption("Email");
		tfEmail.setImmediate(false);
		tfEmail.setWidth("-1px");
		tfEmail.setHeight("-1px");
		tfEmail.setSizeFull();
		fields.addComponent(tfEmail, 2, 4);

		// txtSite
		tfSite = new TextField();
		tfSite.setCaption("Site");
		tfSite.setImmediate(false);
		tfSite.setWidth("-1px");
		tfSite.setHeight("-1px");
		tfSite.setSizeFull();
		fields.addComponent(tfSite, 3, 4);

		// mocPessoa
		mocPessoa = new ManyToOneCombo<>();
		mocPessoa.setCaption("Pessoa");
		mocPessoa.setWidth("120px");
		mocPessoa.setHeight("-1px");
		mocPessoa.setSizeFull();
		fields.addComponent(mocPessoa, 4, 0);

		return fields;
	}
}