package dc.visao.geral.outro;

import org.vaadin.addons.maskedtextfield.MaskedTextField;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.geral.outro.ConvenioFormController;
import dc.entidade.geral.diverso.UfEntity;
import dc.entidade.geral.pessoal.PessoaEntity;
import dc.visao.framework.component.manytoonecombo.ManyToOneCombo;
import dc.visao.framework.util.ComponentUtil;

public class ConvenioFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private GridLayout fields;

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private TextArea tfDescricao;

	@AutoGenerated
	private PopupDateField pdfDataCadastro;

	@AutoGenerated
	private MaskedTextField tfTelefone, tfContato, tfCep, tfCnpj;


	@AutoGenerated
	private ManyToOneCombo<UfEntity> mocUf;

	@AutoGenerated
	private ManyToOneCombo<PessoaEntity> mocPessoa;

	@AutoGenerated
	private TextField tfMunicipioIBGE;

	@AutoGenerated
	private TextField tfBairro;

	@AutoGenerated
	private TextField tfNumero;

	@AutoGenerated
	private TextField tfLogradouro;

	@AutoGenerated
	private PopupDateField pdfDataVencimento;

	@AutoGenerated
	private TextField tfDesconto;

	@AutoGenerated
	private TextField tfNome;

	@AutoGenerated
	private TextField tfEmail;

	@AutoGenerated
	private TextField tfSite;

	private ConvenioFormController controller;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public ConvenioFormView(ConvenioFormController controller) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.controller = controller;
	}

	public MaskedTextField getTfCep() {
		return tfCep;
	}

	public void setTfCep(MaskedTextField tfCep) {
		this.tfCep = tfCep;
	}

	public TextArea getTfDescricao() {
		return tfDescricao;
	}

	public void setTfDescricao(TextArea tfDescricao) {
		this.tfDescricao = tfDescricao;
	}

	public PopupDateField getPdfDataCadastro() {
		return pdfDataCadastro;
	}

	public void setPdfDataCadastro(PopupDateField pdfDataCadastro) {
		this.pdfDataCadastro = pdfDataCadastro;
	}

	public MaskedTextField getTfTelefone() {
		return tfTelefone;
	}

	public void setTfTelefone(MaskedTextField tfTelefone) {
		this.tfTelefone = tfTelefone;
	}

	public MaskedTextField getTfContato() {
		return tfContato;
	}

	public void setTfContato(MaskedTextField tfContato) {
		this.tfContato = tfContato;
	}

	public ManyToOneCombo<UfEntity> getMocUf() {
		return mocUf;
	}

	public void setMocUf(ManyToOneCombo<UfEntity> mocUf) {
		this.mocUf = mocUf;
	}

	public ManyToOneCombo<PessoaEntity> getMocPessoa() {
		return mocPessoa;
	}

	public void setMocPessoa(ManyToOneCombo<PessoaEntity> mocPessoa) {
		this.mocPessoa = mocPessoa;
	}

	public TextField getTfMunicipioIBGE() {
		return tfMunicipioIBGE;
	}

	public void setTfMunicipioIBGE(TextField tfMunicipioIBGE) {
		this.tfMunicipioIBGE = tfMunicipioIBGE;
	}

	public TextField getTfBairro() {
		return tfBairro;
	}

	public void setTfBairro(TextField tfBairro) {
		this.tfBairro = tfBairro;
	}

	public TextField getTfNumero() {
		return tfNumero;
	}

	public void setTfNumero(TextField tfNumero) {
		this.tfNumero = tfNumero;
	}

	public TextField getTfLogradouro() {
		return tfLogradouro;
	}

	public void setTfLogradouro(TextField tfLogradouro) {
		this.tfLogradouro = tfLogradouro;
	}

	public PopupDateField getPdfDataVencimento() {
		return pdfDataVencimento;
	}

	public void setPdfDataVencimento(PopupDateField pdfDataVencimento) {
		this.pdfDataVencimento = pdfDataVencimento;
	}

	public TextField getTfDesconto() {
		return tfDesconto;
	}

	public void setTfDesconto(TextField tfDesconto) {
		this.tfDesconto = tfDesconto;
	}

	public TextField getTfNome() {
		return tfNome;
	}

	public void setTfNome(TextField tfNome) {
		this.tfNome = tfNome;
	}

	public MaskedTextField getTfCnpj() {
		return tfCnpj;
	}

	public void setTfCnpj(MaskedTextField tfCnpj) {
		this.tfCnpj = tfCnpj;
	}

	public TextField getTfEmail() {
		return tfEmail;
	}

	public void setTfEmail(TextField tfEmail) {
		this.tfEmail = tfEmail;
	}

	public TextField getTfSite() {
		return tfSite;
	}

	public void setTfSite(TextField tfSite) {
		this.tfSite = tfSite;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		// setHeight("100.0%");

		fields = buildFields();

		mainLayout.addComponent(fields);

		return mainLayout;
	}

	private GridLayout buildFields() {
		fields = new GridLayout();
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		fields.setRows(9);
		fields.setColumns(9);

		// mocPessoa
		mocPessoa = new ManyToOneCombo<>();
		mocPessoa.setCaption("Pessoa");
		mocPessoa.setWidth("300px");
		mocPessoa.setHeight("-1px");
		fields.addComponent(mocPessoa, 0, 0);
		
		// txtNome
		tfNome = ComponentUtil.buildTextField("Nome");
		tfNome.setImmediate(false);
		tfNome.setRequired(true);
		tfNome.setWidth("500px");
		tfNome.setHeight("-1px");
		fields.addComponent(tfNome, 0, 1);
		
		// txtCnpj
		tfCnpj = ComponentUtil.buildMaskedTextField("CNPJ", "##.###.###/####-##");
		tfCnpj.setMaskClientOnly(true);
		tfCnpj.setImmediate(false);
		tfCnpj.setWidth("200px");
		tfCnpj.setHeight("-1px");
		fields.addComponent(tfCnpj, 1, 1);
		
		// txtLogradouro
		tfLogradouro = ComponentUtil.buildTextField("Logradouro");
		tfLogradouro.setImmediate(false);
		tfLogradouro.setRequired(true);
		tfLogradouro.setWidth("500px");
		tfLogradouro.setHeight("-1px");
		fields.addComponent(tfLogradouro, 0, 2);
		
		// txtNumero
		tfNumero = ComponentUtil.buildTextField("Número");
		tfNumero.setImmediate(false);
		tfNumero.setWidth("100px");
		tfNumero.setHeight("-1px");
		fields.addComponent(tfNumero, 1, 2);
		
		// txtBairro
		tfBairro = ComponentUtil.buildTextField("Bairro");
		tfBairro.setImmediate(false);
		tfBairro.setWidth("250px");
		tfBairro.setHeight("-1px");
		fields.addComponent(tfBairro, 2, 2);
			
		// txtMunicipioIBGE
		tfMunicipioIBGE = ComponentUtil.buildTextField("Municipio IBGE");
		tfMunicipioIBGE.setImmediate(false);
		tfMunicipioIBGE.setWidth("200px");
		tfMunicipioIBGE.setHeight("-1px");
		fields.addComponent(tfMunicipioIBGE, 3, 2);
		
		// txtCep
		tfCep = ComponentUtil.buildMaskedTextField("CEP", "#####-###");
		tfCep.setMaskClientOnly(true);
		tfCep.setImmediate(false);
		tfCep.setWidth("250px");
		tfCep.setHeight("-1px");
		fields.addComponent(tfCep, 0, 3);
		
		// cmbUF
		mocUf = new ManyToOneCombo<>();
		mocUf.setCaption("UF");
		mocUf.setWidth("120px");
		mocUf.setHeight("-1px");
		fields.addComponent(mocUf, 1, 3);
			
				
		// txtDesconto
		tfDesconto = ComponentUtil.buildTextField("Desconto");
		tfDesconto.setImmediate(false);
		tfDesconto.setWidth("-1px");
		tfDesconto.setHeight("-1px");
		fields.addComponent(tfDesconto, 0, 4);

		// dnDataVencimento
		pdfDataVencimento = ComponentUtil.buildPopupDateField("Data Vencimento");
		pdfDataVencimento.setImmediate(false);
		pdfDataVencimento.setWidth("200px");
		pdfDataVencimento.setHeight("-1px");
		fields.addComponent(pdfDataVencimento, 1, 4);
		
		// dnDataCadastro
		pdfDataCadastro = ComponentUtil.buildPopupDateField("Data Cadastro");
		pdfDataCadastro.setImmediate(false);
		pdfDataCadastro.setWidth("200px");
		pdfDataCadastro.setHeight("-1px");
		fields.addComponent(pdfDataCadastro, 2, 4);


		// txtContato
		tfContato = ComponentUtil.buildMaskedTextField("Contato", "(##) #####-####");
		tfContato.setMaskClientOnly(true);
		tfContato.setImmediate(false);
		tfContato.setWidth("-1px");
		tfContato.setHeight("-1px");
		fields.addComponent(tfContato, 0, 5);

		// txtTelefone
		tfTelefone = ComponentUtil.buildMaskedTextField("Telefone", "(##) #####-####");
		tfTelefone.setMaskClientOnly(true);
		tfTelefone.setImmediate(false);
		tfTelefone.setWidth("-1px");
		tfTelefone.setHeight("-1px");
		fields.addComponent(tfTelefone, 1, 5);
		
		// txtEmail
		tfEmail = ComponentUtil.buildTextField("Email");
		tfEmail.setImmediate(false);
		tfEmail.setWidth("300px");
		tfEmail.setHeight("-1px");
		fields.addComponent(tfEmail, 0, 6);

		// txtSite
		tfSite = ComponentUtil.buildTextField("Site");
		tfSite.setImmediate(false);
		tfSite.setWidth("300px");
		tfSite.setHeight("-1px");
		fields.addComponent(tfSite, 1, 6);

		// txtDescricao
		tfDescricao = ComponentUtil.buildTextArea("Descrição");
		tfDescricao.setImmediate(false);
		tfDescricao.setWidth("540px");
		tfDescricao.setHeight("-1px");
		fields.addComponent(tfDescricao, 0, 7);

		return fields;
	}
}