package dc.visao.pessoal;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.pessoal.ContadorFormController;
import dc.entidade.geral.Pessoa;
import dc.visao.framework.component.manytoonecombo.ManyToOneCombo;
import dc.visao.framework.util.ComponentUtil;

public class ContadorFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private GridLayout fields;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtFax;
	@AutoGenerated
	private TextField txtTelefone;

	@AutoGenerated
	private ComboBox cmbUf;

	@AutoGenerated
	private TextField txtMunicipioIbge;
	@AutoGenerated
	private TextField txtBairro;
	@AutoGenerated
	private TextField txtNumero;
	@AutoGenerated
	private TextField txtComplemento;
	@AutoGenerated
	private TextField txtCep;
	@AutoGenerated
	private TextField txtLogradouro;
	@AutoGenerated
	private TextField txtUfCRC;
	@AutoGenerated
	private TextField txtNumeroCRC;
	@AutoGenerated
	private ManyToOneCombo<Pessoa> cmbPessoa;
	
	ContadorFormController controller;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public ContadorFormView(ContadorFormController controller) {
		this.controller = controller;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {

		// common part: create layout
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		// setHeight("100.0%");

		fields = buildFields();

		mainLayout.addComponent(fields);
	
		return mainLayout;
	}

	
	private GridLayout buildFields() {
		fields = new GridLayout();
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);
		fields.setRows(5);
		fields.setColumns(5);

		// cmbPessoa
		cmbPessoa = new ManyToOneCombo<>();
		cmbPessoa.setCaption("Pessoa");
		fields.addComponent(cmbPessoa, 0, 0);

		// txtNumeroCRC
		txtNumeroCRC = new TextField();
		txtNumeroCRC.setCaption("Número CRC");
		txtNumeroCRC.setImmediate(false);
		txtNumeroCRC.setWidth("120px");
		txtNumeroCRC.setHeight("-1px");
		txtNumeroCRC.setSizeFull();
		fields.addComponent(txtNumeroCRC, 0, 1);

		// txtUfCRC
		txtUfCRC = new TextField();
		txtUfCRC.setCaption("Uf CRC");
		txtUfCRC.setImmediate(false);
		txtUfCRC.setWidth("113px");
		txtUfCRC.setHeight("-1px");
		txtUfCRC.setSizeFull();
		fields.addComponent(txtUfCRC, 1, 1);

		// txtLogradouro
		txtLogradouro = new TextField();
		txtLogradouro.setCaption("Logradouro");
		txtLogradouro.setImmediate(false);
		txtLogradouro.setWidth("435px");
		txtLogradouro.setHeight("-1px");
		txtLogradouro.setRequired(true);
		txtLogradouro.setSizeFull();
		fields.addComponent(txtLogradouro, 2, 1);

		// txtCep
		txtCep = new TextField();
		txtCep.setCaption("CEP");
		txtCep.setImmediate(false);
		txtCep.setWidth("-1px");
		txtCep.setHeight("-1px");
		txtCep.setSizeFull();
		fields.addComponent(txtCep, 0, 2);

		// txtComplemento
		txtComplemento = new TextField();
		txtComplemento.setCaption("Complemento");
		txtComplemento.setImmediate(false);
		txtComplemento.setWidth("393px");
		txtComplemento.setHeight("-1px");
		txtComplemento.setSizeFull();
		fields.addComponent(txtComplemento, 1, 2);

		// txtNumero
		txtNumero = new TextField();
		txtNumero.setCaption("Número");
		txtNumero.setImmediate(false);
		txtNumero.setWidth("134px");
		txtNumero.setHeight("-1px");
		txtNumero.setSizeFull();
		fields.addComponent(txtNumero, 2, 2);

		// txtBairro
		txtBairro = new TextField();
		txtBairro.setCaption("Bairro");
		txtBairro.setImmediate(false);
		txtBairro.setWidth("180px");
		txtBairro.setHeight("-1px");
		txtBairro.setRequired(true);
		txtBairro.setSizeFull();
		fields.addComponent(txtBairro, 0, 3);

		// txtMunicipioIbge
		txtMunicipioIbge = new TextField();
		txtMunicipioIbge.setCaption("Município IBGE");
		txtMunicipioIbge.setImmediate(false);
		txtMunicipioIbge.setWidth("134px");
		txtMunicipioIbge.setHeight("-1px");
		txtMunicipioIbge.setSizeFull();
		fields.addComponent(txtMunicipioIbge, 1, 3);

		// cmbUf
		cmbUf = ComponentUtil.buildComboBox("UF");
		cmbUf.setContainerDataSource(controller.carregarUFs());
		cmbUf.setWidth("100px");
		cmbUf.setHeight("-1px");
		fields.addComponent(cmbUf, 2, 3);

		// txtTelefone
		txtTelefone = new TextField();
		txtTelefone.setCaption("Telefone");
		txtTelefone.setImmediate(false);
		txtTelefone.setWidth("-1px");
		txtTelefone.setHeight("-1px");
		txtTelefone.setSizeFull();
		fields.addComponent(txtTelefone, 0, 4);

		// txtFax
		txtFax = new TextField();
		txtFax.setCaption("Fax");
		txtFax.setImmediate(false);
		txtFax.setWidth("127px");
		txtFax.setHeight("-1px");
		txtFax.setSizeFull();
		fields.addComponent(txtFax, 1, 4);

		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("Email");
		txtEmail.setImmediate(false);
		txtEmail.setWidth("680px");
		txtEmail.setHeight("-1px");
		txtEmail.setSizeFull();
		fields.addComponent(txtEmail, 2, 4);

		return fields;
	}

	public GridLayout getFields() {
		return fields;
	}

	public void setFields(GridLayout fields) {
		this.fields = fields;
	}

	public VerticalLayout getVerticalLayout() {
		return mainLayout;
	}

	public void setVerticalLayout(VerticalLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

	public TextField getTxtEmail() {
		return txtEmail;
	}

	public void setTxtEmail(TextField txtEmail) {
		this.txtEmail = txtEmail;
	}

	public TextField getTxtFax() {
		return txtFax;
	}

	public void setTxtFax(TextField txtFax) {
		this.txtFax = txtFax;
	}

	public TextField getTxtTelefone() {
		return txtTelefone;
	}

	public void setTxtTelefone(TextField txtTelefone) {
		this.txtTelefone = txtTelefone;
	}

	public ComboBox getCmbUf() {
		return cmbUf;
	}

	public void setCmbUf(ComboBox cmbUf) {
		this.cmbUf = cmbUf;
	}

	public TextField getTxtMunicipioIbge() {
		return txtMunicipioIbge;
	}

	public void setTxtMunicipioIbge(TextField txtMunicipioIbge) {
		this.txtMunicipioIbge = txtMunicipioIbge;
	}

	public TextField getTxtBairro() {
		return txtBairro;
	}

	public void setTxtBairro(TextField txtBairro) {
		this.txtBairro = txtBairro;
	}

	public TextField getTxtNumero() {
		return txtNumero;
	}

	public void setTxtNumero(TextField txtNumero) {
		this.txtNumero = txtNumero;
	}

	public TextField getTxtComplemento() {
		return txtComplemento;
	}

	public void setTxtComplemento(TextField txtComplemento) {
		this.txtComplemento = txtComplemento;
	}

	public TextField getTxtCep() {
		return txtCep;
	}

	public void setTxtCep(TextField txtCep) {
		this.txtCep = txtCep;
	}

	public TextField getTxtLogradouro() {
		return txtLogradouro;
	}

	public void setTxtLogradouro(TextField txtLogradouro) {
		this.txtLogradouro = txtLogradouro;
	}

	public TextField getTxtUfCRC() {
		return txtUfCRC;
	}

	public void setTxtUfCRC(TextField txtUfCRC) {
		this.txtUfCRC = txtUfCRC;
	}

	public TextField getTxtNumeroCRC() {
		return txtNumeroCRC;
	}

	public void setTxtNumeroCRC(TextField txtNumeroCRC) {
		this.txtNumeroCRC = txtNumeroCRC;
	}

	public ManyToOneCombo<Pessoa> getCmbPessoa() {
		return cmbPessoa;
	}

	public void setCmbPessoa(ManyToOneCombo<Pessoa> cmbPessoa) {
		this.cmbPessoa = cmbPessoa;
	}

}