package dc.visao.pessoal;

import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;

import dc.entidade.geral.Pessoa;
import dc.entidade.geral.UF;
import dc.visao.framework.component.manytoonecombo.ManyToOneCombo;

public class ContadorFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_5;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private TextField txtFax;
	@AutoGenerated
	private TextField txtTelefone;

	@AutoGenerated
	private ManyToOneCombo<UF> cmbUf;

	@AutoGenerated
	private TextField txtMunicipioIbge;
	@AutoGenerated
	private TextField txtBairro;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private TextField txtNumero;
	@AutoGenerated
	private TextField txtComplemento;
	@AutoGenerated
	private TextField txtCep;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private TextField txtLogradouro;
	@AutoGenerated
	private TextField txtUfCRC;
	@AutoGenerated
	private TextField txtNumeroCRC;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private ManyToOneCombo<Pessoa> cmbPessoa;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public ContadorFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		mainLayout.setRows(5);

		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");

		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, 0, 0);

		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2, 0, 1);

		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3, 0, 2);

		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		mainLayout.addComponent(horizontalLayout_4, 0, 3);

		// horizontalLayout_5
		horizontalLayout_5 = buildHorizontalLayout_5();
		mainLayout.addComponent(horizontalLayout_5, 0, 4);

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);

		// cmbPessoa
		cmbPessoa = new ManyToOneCombo<>();
		cmbPessoa.setCaption("Pessoa");
		cmbPessoa.setImmediate(false);
		cmbPessoa.setWidth("680px");
		cmbPessoa.setHeight("-1px");
		horizontalLayout_1.addComponent(cmbPessoa);

		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);

		// txtNumeroCRC
		txtNumeroCRC = new TextField();
		txtNumeroCRC.setCaption("Número CRC");
		txtNumeroCRC.setImmediate(false);
		txtNumeroCRC.setWidth("120px");
		txtNumeroCRC.setHeight("-1px");
		horizontalLayout_2.addComponent(txtNumeroCRC);

		// txtUfCRC
		txtUfCRC = new TextField();
		txtUfCRC.setCaption("Uf CRC");
		txtUfCRC.setImmediate(false);
		txtUfCRC.setWidth("113px");
		txtUfCRC.setHeight("-1px");
		horizontalLayout_2.addComponent(txtUfCRC);

		// txtLogradouro
		txtLogradouro = new TextField();
		txtLogradouro.setCaption("Logradouro");
		txtLogradouro.setImmediate(false);
		txtLogradouro.setWidth("435px");
		txtLogradouro.setHeight("-1px");
		txtLogradouro.setRequired(true);
		horizontalLayout_2.addComponent(txtLogradouro);

		return horizontalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		horizontalLayout_3.setSpacing(true);

		// txtCep
		txtCep = new TextField();
		txtCep.setCaption("CEP");
		txtCep.setImmediate(false);
		txtCep.setWidth("-1px");
		txtCep.setHeight("-1px");
		horizontalLayout_3.addComponent(txtCep);

		// txtComplemento
		txtComplemento = new TextField();
		txtComplemento.setCaption("Complemento");
		txtComplemento.setImmediate(false);
		txtComplemento.setWidth("393px");
		txtComplemento.setHeight("-1px");
		horizontalLayout_3.addComponent(txtComplemento);

		// txtNumero
		txtNumero = new TextField();
		txtNumero.setCaption("Número");
		txtNumero.setImmediate(false);
		txtNumero.setWidth("134px");
		txtNumero.setHeight("-1px");
		horizontalLayout_3.addComponent(txtNumero);

		return horizontalLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("-1px");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		horizontalLayout_4.setSpacing(true);

		// txtBairro
		txtBairro = new TextField();
		txtBairro.setCaption("Bairro");
		txtBairro.setImmediate(false);
		txtBairro.setWidth("180px");
		txtBairro.setHeight("-1px");
		txtBairro.setRequired(true);
		horizontalLayout_4.addComponent(txtBairro);

		// txtMunicipioIbge
		txtMunicipioIbge = new TextField();
		txtMunicipioIbge.setCaption("Município IBGE");
		txtMunicipioIbge.setImmediate(false);
		txtMunicipioIbge.setWidth("134px");
		txtMunicipioIbge.setHeight("-1px");
		horizontalLayout_4.addComponent(txtMunicipioIbge);

		// cmbUf
		cmbUf = new ManyToOneCombo<>();
		cmbUf.setCaption("UF");
		cmbUf.setImmediate(false);
		cmbUf.setWidth("70px");
		cmbUf.setHeight("-1px");
		horizontalLayout_4.addComponent(cmbUf);

		// txtTelefone
		txtTelefone = new TextField();
		txtTelefone.setCaption("Telefone");
		txtTelefone.setImmediate(false);
		txtTelefone.setWidth("-1px");
		txtTelefone.setHeight("-1px");
		horizontalLayout_4.addComponent(txtTelefone);

		// txtFax
		txtFax = new TextField();
		txtFax.setCaption("Fax");
		txtFax.setImmediate(false);
		txtFax.setWidth("127px");
		txtFax.setHeight("-1px");
		horizontalLayout_4.addComponent(txtFax);

		return horizontalLayout_4;
	}

	public void InitCbs(List<Pessoa> pessoa, List<UF> uf) {
		// BeanItemContainer<Pessoa> objectspessoa = new
		// BeanItemContainer<Pessoa>(Pessoa.class, pessoa);
		// cmbPessoa.setContainerDataSource(objectspessoa);

		// BeanItemContainer<UF> objectsuf = new BeanItemContainer<UF>(UF.class,
		// uf);
		// cmbPessoa.setContainerDataSource(objectsuf);
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_5() {
		// common part: create layout
		horizontalLayout_5 = new HorizontalLayout();
		horizontalLayout_5.setImmediate(false);
		horizontalLayout_5.setWidth("-1px");
		horizontalLayout_5.setHeight("-1px");
		horizontalLayout_5.setMargin(false);
		horizontalLayout_5.setSpacing(true);

		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("Email");
		txtEmail.setImmediate(false);
		txtEmail.setWidth("680px");
		txtEmail.setHeight("-1px");
		horizontalLayout_5.addComponent(txtEmail);

		return horizontalLayout_5;
	}

	public GridLayout getMainLayout() {
		return mainLayout;
	}

	public void setMainLayout(GridLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

	public HorizontalLayout getHorizontalLayout_5() {
		return horizontalLayout_5;
	}

	public void setHorizontalLayout_5(HorizontalLayout horizontalLayout_5) {
		this.horizontalLayout_5 = horizontalLayout_5;
	}

	public TextField getTxtEmail() {
		return txtEmail;
	}

	public void setTxtEmail(TextField txtEmail) {
		this.txtEmail = txtEmail;
	}

	public HorizontalLayout getHorizontalLayout_4() {
		return horizontalLayout_4;
	}

	public void setHorizontalLayout_4(HorizontalLayout horizontalLayout_4) {
		this.horizontalLayout_4 = horizontalLayout_4;
	}

	public TextField getTxtFax() {
		return txtFax;
	}

	public void setTxtFax(TextField txtFax) {
		this.txtFax = txtFax;
	}

	public TextField getTxtTelefone() {
		return txtTelefone;
	}

	public void setTxtTelefone(TextField txtTelefone) {
		this.txtTelefone = txtTelefone;
	}

	public ManyToOneCombo<UF> getCmbUf() {
		return cmbUf;
	}

	public void setCmbUf(ManyToOneCombo<UF> cmbUf) {
		this.cmbUf = cmbUf;
	}

	public TextField getTxtMunicipioIbge() {
		return txtMunicipioIbge;
	}

	public void setTxtMunicipioIbge(TextField txtMunicipioIbge) {
		this.txtMunicipioIbge = txtMunicipioIbge;
	}

	public TextField getTxtBairro() {
		return txtBairro;
	}

	public void setTxtBairro(TextField txtBairro) {
		this.txtBairro = txtBairro;
	}

	public HorizontalLayout getHorizontalLayout_3() {
		return horizontalLayout_3;
	}

	public void setHorizontalLayout_3(HorizontalLayout horizontalLayout_3) {
		this.horizontalLayout_3 = horizontalLayout_3;
	}

	public TextField getTxtNumero() {
		return txtNumero;
	}

	public void setTxtNumero(TextField txtNumero) {
		this.txtNumero = txtNumero;
	}

	public TextField getTxtComplemento() {
		return txtComplemento;
	}

	public void setTxtComplemento(TextField txtComplemento) {
		this.txtComplemento = txtComplemento;
	}

	public TextField getTxtCep() {
		return txtCep;
	}

	public void setTxtCep(TextField txtCep) {
		this.txtCep = txtCep;
	}

	public HorizontalLayout getHorizontalLayout_2() {
		return horizontalLayout_2;
	}

	public void setHorizontalLayout_2(HorizontalLayout horizontalLayout_2) {
		this.horizontalLayout_2 = horizontalLayout_2;
	}

	public TextField getTxtLogradouro() {
		return txtLogradouro;
	}

	public void setTxtLogradouro(TextField txtLogradouro) {
		this.txtLogradouro = txtLogradouro;
	}

	public TextField getTxtUfCRC() {
		return txtUfCRC;
	}

	public void setTxtUfCRC(TextField txtUfCRC) {
		this.txtUfCRC = txtUfCRC;
	}

	public TextField getTxtNumeroCRC() {
		return txtNumeroCRC;
	}

	public void setTxtNumeroCRC(TextField txtNumeroCRC) {
		this.txtNumeroCRC = txtNumeroCRC;
	}

	public HorizontalLayout getHorizontalLayout_1() {
		return horizontalLayout_1;
	}

	public void setHorizontalLayout_1(HorizontalLayout horizontalLayout_1) {
		this.horizontalLayout_1 = horizontalLayout_1;
	}

	public ManyToOneCombo<Pessoa> getCmbPessoa() {
		return cmbPessoa;
	}

	public void setCmbPessoa(ManyToOneCombo<Pessoa> cmbPessoa) {
		this.cmbPessoa = cmbPessoa;
	}

}