package dc.visao.geral.pessoal;

import java.util.List;

import org.vaadin.addons.maskedtextfield.MaskedTextField;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Field;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TableFieldFactory;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.control.enums.TipoPessoaEn;
import dc.controller.geral.pessoal.PessoaFormController;
import dc.entidade.geral.PessoaContatoEntity;
import dc.entidade.geral.PessoaEnderecoEntity;
import dc.entidade.geral.pessoal.EstadoCivilEntity;
import dc.visao.framework.component.IntegerConverter;
import dc.visao.framework.component.SubFormComponent;
import dc.visao.framework.component.manytoonecombo.ManyToOneCombo;
import dc.visao.framework.util.ComponentUtil;

public class PessoaFormView extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private GridLayout fields;

	@AutoGenerated
	private GridLayout layoutFisica;

	@AutoGenerated
	private GridLayout layoutJuridica;

	@AutoGenerated
	private TabSheet subForms;

	@AutoGenerated
	private ComboBox cbTipoPessoa;

	@AutoGenerated
	private ComboBox cbRaca;

	@AutoGenerated
	private ComboBox cbTipoSanguineo;

	@AutoGenerated
	private ComboBox cbTipoRegime;

	@AutoGenerated
	private ComboBox cbCrt;

	@AutoGenerated
	private ComboBox cbCategoriaReservista;

	@AutoGenerated
	private ComboBox cbCategoriaCnh;

	@AutoGenerated
	private TextField txtNome;

	@AutoGenerated
	private TextField txtEmail;

	@AutoGenerated
	private TextField txtSite;

	@AutoGenerated
	private MaskedTextField txtCpf;

	@AutoGenerated
	private PopupDateField dataNascimento;

	@AutoGenerated
	private TextField txtNaturalidade;

	@AutoGenerated
	private TextField txtNacionalidade;

	@AutoGenerated
	private TextField txtNomePai;

	@AutoGenerated
	private TextField txtNomeMae;

	@AutoGenerated
	private TextField txtFantasia;

	@AutoGenerated
	private TextField txtCnpj;

	@AutoGenerated
	private TextField txtInscricaoEstadual;

	@AutoGenerated
	private TextField txtInscricaoMunicipal;

	@AutoGenerated
	private PopupDateField dataConstituicao;

	@AutoGenerated
	private TextField txtSuframa;

	@AutoGenerated
	private TextField txtNumeroRg;

	@AutoGenerated
	private TextField txtEmissorRg;

	@AutoGenerated
	private TextField txtOrgaoEmissor;

	@AutoGenerated
	private TextField txtCnh;

	@AutoGenerated
	private TextField txtTituloEleitor;

	@AutoGenerated
	private TextField txtTituloZona;

	@AutoGenerated
	private TextField txtTituloSecao;

	@AutoGenerated
	private PopupDateField dataCnhEmissao;

	@AutoGenerated
	private TextField txtNumeroReservista;

	@AutoGenerated
	private PopupDateField dataEmissaoRg;

	@AutoGenerated
	private OptionGroup ogSexo;

	@AutoGenerated
	private OptionGroup ogCategoriaPessoa;

	@AutoGenerated
	private ManyToOneCombo<EstadoCivilEntity> mocEstadoCivil;

	private SubFormComponent<PessoaContatoEntity, Integer> sfPessoaContato;

	private SubFormComponent<PessoaEnderecoEntity, Integer> sfPessoaEndereco;

	private PessoaFormController controller;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public PessoaFormView(PessoaFormController controller) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.controller = controller;
	}

	public ComboBox getCbTipoPessoa() {
		return cbTipoPessoa;
	}

	public void setCbTipoPessoa(ComboBox cbTipoPessoa) {
		this.cbTipoPessoa = cbTipoPessoa;
	}

	public ComboBox getCbRaca() {
		return cbRaca;
	}

	public void setCbRaca(ComboBox cbRaca) {
		this.cbRaca = cbRaca;
	}

	public ComboBox getCbTipoSanguineo() {
		return cbTipoSanguineo;
	}

	public void setCbTipoSanguineo(ComboBox cbTipoSanguineo) {
		this.cbTipoSanguineo = cbTipoSanguineo;
	}

	public ComboBox getCbTipoRegime() {
		return cbTipoRegime;
	}

	public void setCbTipoRegime(ComboBox cbTipoRegime) {
		this.cbTipoRegime = cbTipoRegime;
	}

	public ComboBox getCbCrt() {
		return cbCrt;
	}

	public void setCbCrt(ComboBox cbCrt) {
		this.cbCrt = cbCrt;
	}

	public ComboBox getCbCategoriaReservista() {
		return cbCategoriaReservista;
	}

	public void setCbCategoriaReservista(ComboBox cbCategoriaReservista) {
		this.cbCategoriaReservista = cbCategoriaReservista;
	}

	public ComboBox getCbCategoriaCnh() {
		return cbCategoriaCnh;
	}

	public void setCbCategoriaCnh(ComboBox cbCategoriaCnh) {
		this.cbCategoriaCnh = cbCategoriaCnh;
	}

	public TextField getTxtNome() {
		return txtNome;
	}

	public void setTxtNome(TextField txtNome) {
		this.txtNome = txtNome;
	}

	public TextField getTxtEmail() {
		return txtEmail;
	}

	public void setTxtEmail(TextField txtEmail) {
		this.txtEmail = txtEmail;
	}

	public TextField getTxtSite() {
		return txtSite;
	}

	public void setTxtSite(TextField txtSite) {
		this.txtSite = txtSite;
	}

	public MaskedTextField getTxtCpf() {
		return txtCpf;
	}

	public void setTxtCpf(MaskedTextField txtCpf) {
		this.txtCpf = txtCpf;
	}

	public PopupDateField getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(PopupDateField dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public TextField getTxtNaturalidade() {
		return txtNaturalidade;
	}

	public void setTxtNaturalidade(TextField txtNaturalidade) {
		this.txtNaturalidade = txtNaturalidade;
	}

	public TextField getTxtNacionalidade() {
		return txtNacionalidade;
	}

	public void setTxtNacionalidade(TextField txtNacionalidade) {
		this.txtNacionalidade = txtNacionalidade;
	}

	public TextField getTxtNomePai() {
		return txtNomePai;
	}

	public void setTxtNomePai(TextField txtNomePai) {
		this.txtNomePai = txtNomePai;
	}

	public TextField getTxtNomeMae() {
		return txtNomeMae;
	}

	public void setTxtNomeMae(TextField txtNomeMae) {
		this.txtNomeMae = txtNomeMae;
	}

	public TextField getTxtFantasia() {
		return txtFantasia;
	}

	public void setTxtFantasia(TextField txtFantasia) {
		this.txtFantasia = txtFantasia;
	}

	public TextField getTxtCnpj() {
		return txtCnpj;
	}

	public void setTxtCnpj(TextField txtCnpj) {
		this.txtCnpj = txtCnpj;
	}

	public TextField getTxtInscricaoEstadual() {
		return txtInscricaoEstadual;
	}

	public void setTxtInscricaoEstadual(TextField txtInscricaoEstadual) {
		this.txtInscricaoEstadual = txtInscricaoEstadual;
	}

	public TextField getTxtInscricaoMunicipal() {
		return txtInscricaoMunicipal;
	}

	public void setTxtInscricaoMunicipal(TextField txtInscricaoMunicipal) {
		this.txtInscricaoMunicipal = txtInscricaoMunicipal;
	}

	public PopupDateField getDataConstituicao() {
		return dataConstituicao;
	}

	public void setDataConstituicao(PopupDateField dataConstituicao) {
		this.dataConstituicao = dataConstituicao;
	}

	public TextField getTxtSuframa() {
		return txtSuframa;
	}

	public void setTxtSuframa(TextField txtSuframa) {
		this.txtSuframa = txtSuframa;
	}

	public TextField getTxtNumeroRg() {
		return txtNumeroRg;
	}

	public void setTxtNumeroRg(TextField txtNumeroRg) {
		this.txtNumeroRg = txtNumeroRg;
	}

	public TextField getTxtEmissorRg() {
		return txtEmissorRg;
	}

	public void setTxtEmissorRg(TextField txtEmissorRg) {
		this.txtEmissorRg = txtEmissorRg;
	}

	public TextField getTxtOrgaoEmissor() {
		return txtOrgaoEmissor;
	}

	public void setTxtOrgaoEmissor(TextField txtOrgaoEmissor) {
		this.txtOrgaoEmissor = txtOrgaoEmissor;
	}

	public TextField getTxtCnh() {
		return txtCnh;
	}

	public void setTxtCnh(TextField txtCnh) {
		this.txtCnh = txtCnh;
	}

	public TextField getTxtTituloEleitor() {
		return txtTituloEleitor;
	}

	public void setTxtTituloEleitor(TextField txtTituloEleitor) {
		this.txtTituloEleitor = txtTituloEleitor;
	}

	public TextField getTxtTituloZona() {
		return txtTituloZona;
	}

	public void setTxtTituloZona(TextField txtTituloZona) {
		this.txtTituloZona = txtTituloZona;
	}

	public TextField getTxtTituloSecao() {
		return txtTituloSecao;
	}

	public void setTxtTituloSecao(TextField txtTituloSecao) {
		this.txtTituloSecao = txtTituloSecao;
	}

	public PopupDateField getDataCnhEmissao() {
		return dataCnhEmissao;
	}

	public void setDataCnhEmissao(PopupDateField dataCnhEmissao) {
		this.dataCnhEmissao = dataCnhEmissao;
	}

	public TextField getTxtNumeroReservista() {
		return txtNumeroReservista;
	}

	public void setTxtNumeroReservista(TextField txtNumeroReservista) {
		this.txtNumeroReservista = txtNumeroReservista;
	}

	public PopupDateField getDataEmissaoRg() {
		return dataEmissaoRg;
	}

	public void setDataEmissaoRg(PopupDateField dataEmissaoRg) {
		this.dataEmissaoRg = dataEmissaoRg;
	}

	public OptionGroup getOgSexo() {
		return ogSexo;
	}

	public void setOgSexo(OptionGroup ogSexo) {
		this.ogSexo = ogSexo;
	}

	public OptionGroup getOgCategoriaPessoa() {
		return ogCategoriaPessoa;
	}

	public void setOgCategoriaPessoa(OptionGroup ogCategoriaPessoa) {
		this.ogCategoriaPessoa = ogCategoriaPessoa;
	}

	public ManyToOneCombo<EstadoCivilEntity> getMocEstadoCivil() {
		return mocEstadoCivil;
	}

	public void setMocEstadoCivil(
			ManyToOneCombo<EstadoCivilEntity> mocEstadoCivil) {
		this.mocEstadoCivil = mocEstadoCivil;
	}

	public SubFormComponent<PessoaContatoEntity, Integer> getSfPessoaContato() {
		return sfPessoaContato;
	}

	public void setSfPessoaContato(
			SubFormComponent<PessoaContatoEntity, Integer> sfPessoaContato) {
		this.sfPessoaContato = sfPessoaContato;
	}

	public SubFormComponent<PessoaEnderecoEntity, Integer> getSfPessoaEndereco() {
		return sfPessoaEndereco;
	}

	public void setSfPessoaEndereco(
			SubFormComponent<PessoaEnderecoEntity, Integer> sfPessoaEndereco) {
		this.sfPessoaEndereco = sfPessoaEndereco;
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		setSizeFull();
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setSizeFull();
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		setWidth("100.0%");

		fields = buildFields();
		mainLayout.addComponent(fields);

		subForms = new TabSheet();

		buildAbaInformacoes();
		buildAbaContatos();
		buildAbaEnderecos();

		mainLayout.addComponent(subForms);
		mainLayout.setExpandRatio(subForms, 1);
	}

	public void buildAbaInformacoes() {
		subForms = new TabSheet();
		subForms.setImmediate(true);
		subForms.setSizeFull();
		VerticalLayout verticalLayout = new VerticalLayout();

		verticalLayout.addComponent(montaLayoutFisica());
		verticalLayout.addComponent(montaLayoutJuridica());

		layoutFisica.setVisible(true);
		layoutJuridica.setVisible(false);

		subForms.addTab(verticalLayout, "Informações do tipo de pessoa", null);

	}

	public void buildAbaContatos() {
		subForms.addTab(buildPessoaContatoSubForm(), "Contato", null);
	}

	// private TabSheet buildContatosSubForm() {
	// // common part: create layout
	// TabSheet sub = new TabSheet();
	// sub.setWidth("100.0%");
	// sub.setHeight("100.0%");
	// sub.setSizeFull();
	// sub.setImmediate(true);
	// sub.addTab(null, "Contatos", null);
	// return sub;
	// }

	public void buildAbaEnderecos() {
		subForms.addTab(buildPessoaEnderecoSubForm(), "Endereços", null);
	}

	public GridLayout montaLayoutFisica() {
		layoutFisica = new GridLayout(6, 7);
		layoutFisica.setImmediate(false);
		layoutFisica.setWidth("100.0%");
		layoutFisica.setHeight("-1px");
		layoutFisica.setMargin(true);
		layoutFisica.setSpacing(true);

		txtCpf = ComponentUtil.buildMaskedTextField("CPF", "###.###.###-##");
		dataNascimento = ComponentUtil
				.buildPopupDateField("Data de nascimento");
		dataNascimento.setWidth("112px");
		cbRaca = ComponentUtil.buildComboBox("Raça");
		mocEstadoCivil = new ManyToOneCombo<>();
		mocEstadoCivil.setCaption("Estado civil");
		cbTipoSanguineo = ComponentUtil.buildComboBox("Tipo sanguíneo");

		txtNaturalidade = ComponentUtil.buildTextField("Naturalidade");
		txtNacionalidade = ComponentUtil.buildTextField("Nacionalidade");

		txtNomePai = ComponentUtil.buildTextField("Nome do pai");
		txtNomeMae = ComponentUtil.buildTextField("Nome da mãe");

		layoutFisica.addComponent(txtCpf, 0, 0);
		layoutFisica.addComponent(dataNascimento, 1, 0);
		layoutFisica.addComponent(mocEstadoCivil, 2, 0);
		layoutFisica.addComponent(cbRaca, 3, 0);
		layoutFisica.addComponent(cbTipoSanguineo, 4, 0);

		layoutFisica.addComponent(txtNaturalidade, 0, 1, 1, 1);
		layoutFisica.addComponent(txtNacionalidade, 2, 1, 3, 1);

		layoutFisica.addComponent(txtNomePai, 0, 2, 1, 2);
		layoutFisica.addComponent(txtNomeMae, 2, 2, 3, 2);

		GridLayout layoutRG = buildContentRg();
		layoutFisica.addComponent(layoutRG, 0, 3, 1, 3);

		GridLayout layoutReservista = buildContentReservista();
		layoutFisica.addComponent(layoutReservista, 2, 3, 3, 3);

		ogSexo = new OptionGroup("Sexo");
		layoutFisica.addComponent(ogSexo, 4, 3);

		GridLayout layoutCNH = buildContentCnh();
		layoutFisica.addComponent(layoutCNH, 0, 4, 1, 4);

		GridLayout layoutTitulo = buildContentTituloEleitor();
		layoutFisica.addComponent(layoutTitulo, 2, 4, 3, 4);

		return layoutFisica;
	}

	private GridLayout buildContentTituloEleitor() {
		GridLayout layoutTitulo = new GridLayout(3, 2);
		layoutTitulo.setImmediate(false);
		layoutTitulo.setWidth("100.0%");
		layoutTitulo.setHeight("-1px");
		layoutTitulo.setMargin(false);
		layoutTitulo.setSpacing(true);

		txtTituloEleitor = ComponentUtil.buildTextField("Número");
		txtTituloZona = ComponentUtil.buildNumericField("Zona");
		txtTituloSecao = ComponentUtil.buildNumericField("Seção");
		txtTituloZona.setConverter(new IntegerConverter());
		txtTituloZona.setMaxLength(10);
		txtTituloSecao.setConverter(new IntegerConverter());
		txtTituloSecao.setMaxLength(10);

		Label lblTitulo = new Label("Título Eleitoral");
		layoutTitulo.addComponent(lblTitulo, 0, 0, 1, 0);
		layoutTitulo.addComponent(txtTituloEleitor, 0, 1);
		layoutTitulo.addComponent(txtTituloZona, 1, 1);
		layoutTitulo.addComponent(txtTituloSecao, 2, 1);

		return layoutTitulo;
	}

	private GridLayout buildContentCnh() {
		GridLayout layoutCnh = new GridLayout(3, 2);
		layoutCnh.setImmediate(false);
		layoutCnh.setWidth("100.0%");
		layoutCnh.setHeight("-1px");
		layoutCnh.setMargin(false);
		layoutCnh.setSpacing(true);

		txtCnh = ComponentUtil.buildTextField("Número da CNH");
		dataCnhEmissao = ComponentUtil.buildPopupDateField("Emissão da CNH");
		cbCategoriaCnh = ComponentUtil.buildComboBox("Categoria da CNH");
		Label lblCnh = new Label("CNH");
		layoutCnh.addComponent(lblCnh, 0, 0);
		layoutCnh.addComponent(txtCnh, 0, 1);
		layoutCnh.addComponent(cbCategoriaCnh, 1, 1);
		layoutCnh.addComponent(dataCnhEmissao, 2, 1);

		return layoutCnh;
	}

	private GridLayout buildContentReservista() {
		GridLayout layoutReservista = new GridLayout(2, 2);
		layoutReservista.setImmediate(false);
		layoutReservista.setWidth("100.0%");
		layoutReservista.setHeight("-1px");
		layoutReservista.setMargin(false);
		layoutReservista.setSpacing(true);

		txtNumeroReservista = ComponentUtil.buildTextField("Número");
		cbCategoriaReservista = ComponentUtil.buildComboBox("Categoria");
		Label lblReservista = new Label("Reservista");
		layoutReservista.addComponent(lblReservista, 0, 0);
		layoutReservista.addComponent(txtNumeroReservista, 0, 1);
		layoutReservista.addComponent(cbCategoriaReservista, 1, 1);

		return layoutReservista;
	}

	private GridLayout buildContentRg() {
		GridLayout layoutRg = new GridLayout(3, 2);
		layoutRg.setImmediate(false);
		layoutRg.setWidth("100.0%");
		layoutRg.setHeight("-1px");
		layoutRg.setMargin(false);
		layoutRg.setSpacing(true);

		txtNumeroRg = ComponentUtil.buildTextField("Número do RG");
		dataEmissaoRg = ComponentUtil.buildPopupDateField("Emissão do RG");
		txtOrgaoEmissor = ComponentUtil.buildTextField("Órgão Emissor");
		Label lblRg = new Label("RG");
		layoutRg.addComponent(lblRg, 0, 0);
		layoutRg.addComponent(txtNumeroRg, 0, 1);
		layoutRg.addComponent(txtOrgaoEmissor, 1, 1);
		layoutRg.addComponent(dataEmissaoRg, 2, 1);

		return layoutRg;
	}

	public GridLayout montaLayoutJuridica() {
		layoutJuridica = new GridLayout(8, 7);
		layoutJuridica.setImmediate(false);
		layoutJuridica.setWidth("100.0%");
		layoutJuridica.setHeight("-1px");
		layoutJuridica.setMargin(true);
		layoutJuridica.setSpacing(true);

		txtFantasia = ComponentUtil.buildTextField("Nome fantasia");
		layoutJuridica.addComponent(txtFantasia, 0, 0, 5, 0);

		txtCnpj = ComponentUtil.buildTextField("CNPJ");
		txtInscricaoEstadual = ComponentUtil
				.buildTextField("Inscrição estadual");
		txtInscricaoMunicipal = ComponentUtil
				.buildTextField("Inscrição municipal");
		dataConstituicao = ComponentUtil
				.buildPopupDateField("Data da constituição");
		txtSuframa = ComponentUtil.buildTextField("Suframa");

		layoutJuridica.addComponent(txtCnpj, 0, 1);
		layoutJuridica.addComponent(txtInscricaoEstadual, 1, 1, 2, 1);
		layoutJuridica.addComponent(txtInscricaoMunicipal, 3, 1);
		layoutJuridica.addComponent(dataConstituicao, 4, 1);
		layoutJuridica.addComponent(txtSuframa, 5, 1);

		cbTipoRegime = ComponentUtil.buildComboBox("Tipo de regime");
		cbCrt = ComponentUtil.buildComboBox("CRT");

		layoutJuridica.addComponent(cbTipoRegime, 0, 2, 2, 2);
		layoutJuridica.addComponent(cbCrt, 3, 2, 4, 2);

		return layoutJuridica;
	}

	@AutoGenerated
	private GridLayout buildFields() {
		// common part: create layout
		fields = new GridLayout(6, 3);
		fields.setImmediate(false);
		fields.setWidth("100.0%");
		fields.setHeight("-1px");
		fields.setMargin(false);
		fields.setSpacing(true);

		txtNome = ComponentUtil.buildTextField("Nome");
		txtNome.setRequired(true);
		fields.addComponent(txtNome, 0, 0, 2, 0);

		cbTipoPessoa = new ComboBox("Tipo de pessoa");
		cbTipoPessoa.setNullSelectionAllowed(false);
		// cmbTipoPessoa.setValue(cmbTipoPessoa.getItemIds().iterator().next());
		// cmbTipoPessoa.setItemCaptionPropertyId("label");
		cbTipoPessoa.setRequired(true);
		cbTipoPessoa.setImmediate(true);
		cbTipoPessoa.addValueChangeListener(new Property.ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				TipoPessoaEn p = (TipoPessoaEn) event.getProperty().getValue();

				if (p.equals(TipoPessoaEn.F)) {
					layoutFisica.setVisible(true);
					layoutJuridica.setVisible(false);
				}

				if (p.equals(TipoPessoaEn.J)) {
					layoutFisica.setVisible(false);
					layoutJuridica.setVisible(true);
				}
			}

		});

		fields.addComponent(cbTipoPessoa, 3, 0);

		txtEmail = ComponentUtil.buildTextField("Email");
		txtEmail.setHeight("30");
		fields.addComponent(txtEmail, 0, 1, 2, 1);

		txtSite = ComponentUtil.buildTextField("Site");
		txtSite.setHeight("30");
		fields.addComponent(txtSite, 3, 1);

		ogCategoriaPessoa = new OptionGroup("");
		ogCategoriaPessoa.setMultiSelect(true);
		ogCategoriaPessoa.setStyleName("v-select-optiongroup-horizontal");
		fields.addComponent(ogCategoriaPessoa, 0, 2, 5, 2);

		return fields;
	}

	/**
	 * SUBFORM
	 */

	private SubFormComponent<PessoaContatoEntity, Integer> buildPessoaContatoSubForm() {
		// common part: create layout

		sfPessoaContato = new SubFormComponent<PessoaContatoEntity, Integer>(
				PessoaContatoEntity.class, new String[] { "nome", "email",
						"foneComercial", "foneResidencial", "foneCelular" },
				new String[] { "Nome", "E-mail", "Telefone comercial",
						"Telefone residencial", "Celular" }) {

			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			protected TableFieldFactory getFieldFactory() {
				return new TableFieldFactory() {

					/**
					 * 
					 */
					private static final long serialVersionUID = 1L;

					@Override
					public Field<?> createField(Container container,
							Object itemId, Object propertyId,
							Component uiContext) {
						if ("nome".equals(propertyId)) {
							TextField textField = ComponentUtil
									.buildTextField("Nome");

							return textField;
						}

						if ("email".equals(propertyId)) {
							TextField textField = ComponentUtil
									.buildTextField("Email");

							return textField;
						}

						if ("foneComercial".equals(propertyId)) {
							MaskedTextField textField = ComponentUtil
									.buildMaskedTextField("Telefone comercial",
											"(##) #####-####");
							textField.setMaskClientOnly(true);

							return textField;
						}

						if ("foneResidencial".equals(propertyId)) {
							MaskedTextField textField = ComponentUtil
									.buildMaskedTextField(
											"Telefone residencial",
											"(##) #####-####");
							textField.setMaskClientOnly(true);

							return textField;
						}

						if ("foneCelular".equals(propertyId)) {
							MaskedTextField textField = ComponentUtil
									.buildMaskedTextField("Celular",
											"(##) #####-####");
							textField.setMaskClientOnly(true);

							return textField;
						}

						return null;
					}

				};
			}

			@Override
			public boolean validateItems(List<PessoaContatoEntity> items) {
				// TODO Auto-generated method stub
				return true;
			}

			protected PessoaContatoEntity getNovo() {
				PessoaContatoEntity detalhe = controller.aderirPessoaContato();

				return detalhe;
			}

			@Override
			protected void getRemoverSelecionados(
					List<PessoaContatoEntity> values) {
				// TODO Auto-generated method stub
				controller.removerPessoaContato(values);
			}

		};

		return sfPessoaContato;
	}

	private SubFormComponent<PessoaEnderecoEntity, Integer> buildPessoaEnderecoSubForm() {
		// common part: create layout
		String[] atributos = new String[] { "cep", "logradouro", "numero",
				"complemento", "bairro", "cidade", "municipioIbge", "fone",
				"fax", "principal", "entrega", "cobranca", "correspondencia" };

		String[] headers = new String[] { "CEP", "Logradouro", "Nº",
				"Complemento", "Bairro", "Cidade", "Município IBGE",
				"Telefone", "Fax", "Principal", "Entrega", "Cobrança",
				"Correspondência" };

		sfPessoaEndereco = new SubFormComponent<PessoaEnderecoEntity, Integer>(
				PessoaEnderecoEntity.class, atributos, headers) {

			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			protected TableFieldFactory getFieldFactory() {
				return new TableFieldFactory() {

					/**
					 * 
					 */
					private static final long serialVersionUID = 1L;

					@Override
					public Field<?> createField(Container container,
							Object itemId, Object propertyId,
							Component uiContext) {
						if ("cep".equals(propertyId)) {
							MaskedTextField textField = ComponentUtil
									.buildMaskedTextField("CEP", "#####-###");
							textField.setMaskClientOnly(true);

							return textField;
						}

						if ("logradouro".equals(propertyId)) {
							TextField textField = ComponentUtil
									.buildTextField("Logradouro");

							return textField;
						}

						if ("numero".equals(propertyId)) {
							TextField textField = ComponentUtil
									.buildTextField("Número");
							textField.setMaxLength(6);
							textField.setConverter(new IntegerConverter());

							return textField;
						}

						if ("complemento".equals(propertyId)) {
							TextField textField = ComponentUtil
									.buildTextField("Complemento");

							return textField;
						}

						if ("bairro".equals(propertyId)) {
							TextField textField = ComponentUtil
									.buildTextField("Bairro");

							return textField;
						}

						if ("cidade".equals(propertyId)) {
							TextField textField = ComponentUtil
									.buildTextField("Cidade");

							return textField;
						}

						if ("municipioIbge".equals(propertyId)) {
							TextField textField = ComponentUtil
									.buildNumericField("Município IBGE");
							textField.setConverter(new IntegerConverter());
							textField.setMaxLength(10);

							return textField;
						}

						// if ("uf".equals(propertyId)) {
						// ComboBox comboBox = ComponentUtil
						// .buildComboBox("UF");
						// ComboBox comboBox = cbUf;

						// BeanItemContainer<UfEntity> bic = new
						// BeanItemContainer<UfEntity>(
						// UfEntity.class, controller.getUfList());
						// comboBox.setContainerDataSource(bic);
						// comboBox.setItemCaptionPropertyId("nome");

						// return comboBox;
						// TextField textField = ComponentUtil
						// .buildTextField("UF");

						// return textField;
						// }

						if ("fone".equals(propertyId)) {
							MaskedTextField textField = ComponentUtil
									.buildMaskedTextField("Telefone",
											"(##) #####-####");
							textField.setMaskClientOnly(true);

							return textField;
						}

						if ("fax".equals(propertyId)) {
							MaskedTextField textField = ComponentUtil
									.buildMaskedTextField("Fax",
											"(##) #####-####");
							textField.setMaskClientOnly(true);

							return textField;
						}

						if ("principal".equals(propertyId)) {
							CheckBox check = ComponentUtil.buildCheckBox(null);

							return check;
						}

						if ("entrega".equals(propertyId)) {
							CheckBox check = ComponentUtil.buildCheckBox(null);

							return check;
						}

						if ("cobranca".equals(propertyId)) {
							CheckBox check = ComponentUtil.buildCheckBox(null);

							return check;
						}

						if ("correspondencia".equals(propertyId)) {
							CheckBox check = ComponentUtil.buildCheckBox(null);

							return check;
						}

						return null;
					}

				};
			}

			@Override
			public boolean validateItems(List<PessoaEnderecoEntity> items) {
				// TODO Auto-generated method stub
				return true;
			}

			protected PessoaEnderecoEntity getNovo() {
				PessoaEnderecoEntity endereco = controller
						.aderirPessoaEndereco();

				return endereco;
			}

			@Override
			protected void getRemoverSelecionados(
					List<PessoaEnderecoEntity> values) {
				// TODO Auto-generated method stub
				controller.removerPessoaEndereco(values);
			}

		};

		return sfPessoaEndereco;
	}

}