package dc.visao.patrimonio;

import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import dc.controller.patrimonio.BemFormController;
import dc.entidade.diversos.Setor;
import dc.entidade.geral.Fornecedor;
import dc.entidade.patrimonio.EstadoConservacaoEntity;
import dc.entidade.patrimonio.GrupoBemEntity;
import dc.entidade.patrimonio.TipoAquisicaoEntity;
import dc.entidade.pessoal.Colaborador;

/**
 * 
 * @author Gutemberg A. Da Silva
 * 
 */

public class BemFormView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Panel panel_1;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private AbsoluteLayout absoluteLayout_1;

	@AutoGenerated
	private ComboBox cbColaborador;

	@AutoGenerated
	private ComboBox cbFornecedor;

	@AutoGenerated
	private ComboBox cbSetor;

	@AutoGenerated
	private ComboBox cbGrupoBem;

	@AutoGenerated
	private ComboBox cbEstadoConservacao;

	@AutoGenerated
	private ComboBox cbTipoAquisicao;

	@AutoGenerated
	private TextField tfFuncao;

	@AutoGenerated
	private TextField tfTaxaDepreciacaoIncentivada;

	@AutoGenerated
	private TextField tfTaxaDepreciacaoAcelerada;

	@AutoGenerated
	private TextField tfTaxaMensalDepreciacao;

	@AutoGenerated
	private TextField tfTaxaAnualDepreciacao;

	@AutoGenerated
	private TextField tfTipoDepreciacao;

	@AutoGenerated
	private PopupDateField pdfUltimaDepreciacao;

	@AutoGenerated
	private PopupDateField pdfInicioDepreciacao;

	@AutoGenerated
	private TextField tfMetodoDepreciacao;

	@AutoGenerated
	private TextField tfDeprecia;

	@AutoGenerated
	private TextField tfValorBaixa;

	@AutoGenerated
	private TextField tfValorAtualizado;

	@AutoGenerated
	private TextField tfValorCompra;

	@AutoGenerated
	private TextField tfValorOriginal;

	@AutoGenerated
	private TextField tfChaveNfe;

	@AutoGenerated
	private TextField tfNumeroNotaFiscal;

	@AutoGenerated
	private PopupDateField pdfVencimentoGarantia;

	@AutoGenerated
	private PopupDateField pdfDataBaixa;

	@AutoGenerated
	private PopupDateField pdfDataMarcacao;

	@AutoGenerated
	private PopupDateField pdfDataVistoria;

	@AutoGenerated
	private PopupDateField pdfDataContabilizado;

	@AutoGenerated
	private PopupDateField pdfDataCadastro;

	@AutoGenerated
	private PopupDateField pdfDataAceite;

	@AutoGenerated
	private PopupDateField pdfDataAquisicao;

	@AutoGenerated
	private TextField tfNumeroSerie;

	@AutoGenerated
	private TextField tfNome;

	@AutoGenerated
	private TextField tfDescricao;

	@AutoGenerated
	private TextField tfNumeroNb;

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private BemFormController controller;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public BemFormView(final BemFormController controller) {
		this.controller = controller;

		buildMainLayout();
		setCompositionRoot(this.mainLayout);
	}

	public TextField getTfNumeroNb() {
		return tfNumeroNb;
	}

	public void setTfNumeroNb(TextField tfNumeroNb) {
		this.tfNumeroNb = tfNumeroNb;
	}

	public TextField getTfNome() {
		return tfNome;
	}

	public void setTfNome(TextField tfNome) {
		this.tfNome = tfNome;
	}

	public TextField getTfDescricao() {
		return tfDescricao;
	}

	public void setTfDescricao(TextField tfDescricao) {
		this.tfDescricao = tfDescricao;
	}

	public TextField getTfNumeroSerie() {
		return tfNumeroSerie;
	}

	public void setTfNumeroSerie(TextField tfNumeroSerie) {
		this.tfNumeroSerie = tfNumeroSerie;
	}

	public PopupDateField getPdfDataAquisicao() {
		return pdfDataAquisicao;
	}

	public void setPdfDataAquisicao(PopupDateField pdfDataAquisicao) {
		this.pdfDataAquisicao = pdfDataAquisicao;
	}

	public PopupDateField getPdfDataAceite() {
		return pdfDataAceite;
	}

	public void setPdfDataAceite(PopupDateField pdfDataAceite) {
		this.pdfDataAceite = pdfDataAceite;
	}

	public PopupDateField getPdfDataCadastro() {
		return pdfDataCadastro;
	}

	public void setPdfDataCadastro(PopupDateField pdfDataCadastro) {
		this.pdfDataCadastro = pdfDataCadastro;
	}

	public PopupDateField getPdfDataContabilizado() {
		return pdfDataContabilizado;
	}

	public void setPdfDataContabilizado(PopupDateField pdfDataContabilizado) {
		this.pdfDataContabilizado = pdfDataContabilizado;
	}

	public PopupDateField getPdfDataVistoria() {
		return pdfDataVistoria;
	}

	public void setPdfDataVistoria(PopupDateField pdfDataVistoria) {
		this.pdfDataVistoria = pdfDataVistoria;
	}

	public PopupDateField getPdfDataMarcacao() {
		return pdfDataMarcacao;
	}

	public void setPdfDataMarcacao(PopupDateField pdfDataMarcacao) {
		this.pdfDataMarcacao = pdfDataMarcacao;
	}

	public PopupDateField getPdfDataBaixa() {
		return pdfDataBaixa;
	}

	public void setPdfDataBaixa(PopupDateField pdfDataBaixa) {
		this.pdfDataBaixa = pdfDataBaixa;
	}

	public PopupDateField getPdfVencimentoGarantia() {
		return pdfVencimentoGarantia;
	}

	public void setPdfVencimentoGarantia(PopupDateField pdfVencimentoGarantia) {
		this.pdfVencimentoGarantia = pdfVencimentoGarantia;
	}

	public TextField getTfNumeroNotaFiscal() {
		return tfNumeroNotaFiscal;
	}

	public void setTfNumeroNotaFiscal(TextField tfNumeroNotaFiscal) {
		this.tfNumeroNotaFiscal = tfNumeroNotaFiscal;
	}

	public TextField getTfChaveNfe() {
		return tfChaveNfe;
	}

	public void setTfChaveNfe(TextField tfChaveNfe) {
		this.tfChaveNfe = tfChaveNfe;
	}

	public TextField getTfValorOriginal() {
		return tfValorOriginal;
	}

	public void setTfValorOriginal(TextField tfValorOriginal) {
		this.tfValorOriginal = tfValorOriginal;
	}

	public TextField getTfValorCompra() {
		return tfValorCompra;
	}

	public void setTfValorCompra(TextField tfValorCompra) {
		this.tfValorCompra = tfValorCompra;
	}

	public TextField getTfValorAtualizado() {
		return tfValorAtualizado;
	}

	public void setTfValorAtualizado(TextField tfValorAtualizado) {
		this.tfValorAtualizado = tfValorAtualizado;
	}

	public TextField getTfValorBaixa() {
		return tfValorBaixa;
	}

	public void setTfValorBaixa(TextField tfValorBaixa) {
		this.tfValorBaixa = tfValorBaixa;
	}

	public TextField getTfDeprecia() {
		return tfDeprecia;
	}

	public void setTfDeprecia(TextField tfDeprecia) {
		this.tfDeprecia = tfDeprecia;
	}

	public TextField getTfMetodoDepreciacao() {
		return tfMetodoDepreciacao;
	}

	public void setTfMetodoDepreciacao(TextField tfMetodoDepreciacao) {
		this.tfMetodoDepreciacao = tfMetodoDepreciacao;
	}

	public PopupDateField getPdfInicioDepreciacao() {
		return pdfInicioDepreciacao;
	}

	public void setPdfInicioDepreciacao(PopupDateField pdfInicioDepreciacao) {
		this.pdfInicioDepreciacao = pdfInicioDepreciacao;
	}

	public PopupDateField getPdfUltimaDepreciacao() {
		return pdfUltimaDepreciacao;
	}

	public void setPdfUltimaDepreciacao(PopupDateField pdfUltimaDepreciacao) {
		this.pdfUltimaDepreciacao = pdfUltimaDepreciacao;
	}

	public TextField getTfTipoDepreciacao() {
		return tfTipoDepreciacao;
	}

	public void setTfTipoDepreciacao(TextField tfTipoDepreciacao) {
		this.tfTipoDepreciacao = tfTipoDepreciacao;
	}

	public TextField getTfTaxaAnualDepreciacao() {
		return tfTaxaAnualDepreciacao;
	}

	public void setTfTaxaAnualDepreciacao(TextField tfTaxaAnualDepreciacao) {
		this.tfTaxaAnualDepreciacao = tfTaxaAnualDepreciacao;
	}

	public TextField getTfTaxaMensalDepreciacao() {
		return tfTaxaMensalDepreciacao;
	}

	public void setTfTaxaMensalDepreciacao(TextField tfTaxaMensalDepreciacao) {
		this.tfTaxaMensalDepreciacao = tfTaxaMensalDepreciacao;
	}

	public TextField getTfTaxaDepreciacaoAcelerada() {
		return tfTaxaDepreciacaoAcelerada;
	}

	public void setTfTaxaDepreciacaoAcelerada(
			TextField tfTaxaDepreciacaoAcelerada) {
		this.tfTaxaDepreciacaoAcelerada = tfTaxaDepreciacaoAcelerada;
	}

	public TextField getTfTaxaDepreciacaoIncentivada() {
		return tfTaxaDepreciacaoIncentivada;
	}

	public void setTfTaxaDepreciacaoIncentivada(
			TextField tfTaxaDepreciacaoIncentivada) {
		this.tfTaxaDepreciacaoIncentivada = tfTaxaDepreciacaoIncentivada;
	}

	public TextField getTfFuncao() {
		return tfFuncao;
	}

	public void setTfFuncao(TextField tfFuncao) {
		this.tfFuncao = tfFuncao;
	}

	public ComboBox getCbTipoAquisicao() {
		return cbTipoAquisicao;
	}

	public void setCbTipoAquisicao(ComboBox cbTipoAquisicao) {
		this.cbTipoAquisicao = cbTipoAquisicao;
	}

	public ComboBox getCbEstadoConservacao() {
		return cbEstadoConservacao;
	}

	public void setCbEstadoConservacao(ComboBox cbEstadoConservacao) {
		this.cbEstadoConservacao = cbEstadoConservacao;
	}

	public ComboBox getCbGrupoBem() {
		return cbGrupoBem;
	}

	public void setCbGrupoBem(ComboBox cbGrupoBem) {
		this.cbGrupoBem = cbGrupoBem;
	}

	public ComboBox getCbSetor() {
		return cbSetor;
	}

	public void setCbSetor(ComboBox cbSetor) {
		this.cbSetor = cbSetor;
	}

	public ComboBox getCbFornecedor() {
		return cbFornecedor;
	}

	public void setCbFornecedor(ComboBox cbFornecedor) {
		this.cbFornecedor = cbFornecedor;
	}

	public ComboBox getCbColaborador() {
		return cbColaborador;
	}

	public void setCbColaborador(ComboBox cbColaborador) {
		this.cbColaborador = cbColaborador;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");

		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		panel_1.setContent(verticalLayout_2);

		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);

		// absoluteLayout_1
		absoluteLayout_1 = buildAbsoluteLayout_1();
		verticalLayout_2.addComponent(absoluteLayout_1);

		return verticalLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_1() {
		// common part: create layout
		absoluteLayout_1 = new AbsoluteLayout();
		absoluteLayout_1.setImmediate(false);
		absoluteLayout_1.setWidth("100.0%");
		absoluteLayout_1.setHeight("1300px");

		// tfNumeroNb
		tfNumeroNb = new TextField();
		tfNumeroNb.setCaption("Número:");
		tfNumeroNb.setImmediate(false);
		tfNumeroNb.setWidth("160px");
		tfNumeroNb.setHeight("-1px");
		absoluteLayout_1.addComponent(tfNumeroNb, "top:50.0px;left:22.0px;");

		// tfDescricao
		tfDescricao = new TextField();
		tfDescricao.setCaption("Descrição:");
		tfDescricao.setImmediate(false);
		tfDescricao.setWidth("160px");
		tfDescricao.setHeight("-1px");
		absoluteLayout_1.addComponent(tfDescricao, "top:50.0px;left:230.0px;");

		// tfNome
		tfNome = new TextField();
		tfNome.setCaption("Nome:");
		tfNome.setImmediate(false);
		tfNome.setWidth("160px");
		tfNome.setHeight("-1px");
		absoluteLayout_1.addComponent(tfNome, "top:50.0px;left:440.0px;");

		// tfNumeroSerie
		tfNumeroSerie = new TextField();
		tfNumeroSerie.setCaption("Número da série:");
		tfNumeroSerie.setImmediate(false);
		tfNumeroSerie.setWidth("160px");
		tfNumeroSerie.setHeight("-1px");
		absoluteLayout_1
				.addComponent(tfNumeroSerie, "top:50.0px;left:660.0px;");

		// pdfDataAquisicao
		pdfDataAquisicao = new PopupDateField();
		pdfDataAquisicao.setCaption("Data da aquisição:");
		pdfDataAquisicao.setImmediate(false);
		pdfDataAquisicao.setWidth("160px");
		pdfDataAquisicao.setHeight("-1px");
		absoluteLayout_1.addComponent(pdfDataAquisicao,
				"top:100.0px;left:22.0px;");

		// pdfDataAceite
		pdfDataAceite = new PopupDateField();
		pdfDataAceite.setCaption("Data do aceite:");
		pdfDataAceite.setImmediate(false);
		pdfDataAceite.setWidth("160px");
		pdfDataAceite.setHeight("-1px");
		absoluteLayout_1.addComponent(pdfDataAceite,
				"top:100.0px;left:230.0px;");

		// pdfDataCadastro
		pdfDataCadastro = new PopupDateField();
		pdfDataCadastro.setCaption("Data de cadastro:");
		pdfDataCadastro.setImmediate(false);
		pdfDataCadastro.setWidth("160px");
		pdfDataCadastro.setHeight("-1px");
		absoluteLayout_1.addComponent(pdfDataCadastro,
				"top:100.0px;left:440.0px;");

		// pdfDataContabilizado
		pdfDataContabilizado = new PopupDateField();
		pdfDataContabilizado.setCaption("Data contabilizado:");
		pdfDataContabilizado.setImmediate(false);
		pdfDataContabilizado.setWidth("160px");
		pdfDataContabilizado.setHeight("-1px");
		absoluteLayout_1.addComponent(pdfDataContabilizado,
				"top:100.0px;left:660.0px;");

		// pdfDataVistoria
		pdfDataVistoria = new PopupDateField();
		pdfDataVistoria.setCaption("Data da vistoria:");
		pdfDataVistoria.setImmediate(false);
		pdfDataVistoria.setWidth("160px");
		pdfDataVistoria.setHeight("-1px");
		absoluteLayout_1.addComponent(pdfDataVistoria,
				"top:150.0px;left:22.0px;");

		// pdfDataMarcacao
		pdfDataMarcacao = new PopupDateField();
		pdfDataMarcacao.setCaption("Data de marcação:");
		pdfDataMarcacao.setImmediate(false);
		pdfDataMarcacao.setWidth("160px");
		pdfDataMarcacao.setHeight("-1px");
		absoluteLayout_1.addComponent(pdfDataMarcacao,
				"top:150.0px;left:230.0px;");

		// pdfDataBaixa
		pdfDataBaixa = new PopupDateField();
		pdfDataBaixa.setCaption("Data da baixa:");
		pdfDataBaixa.setImmediate(false);
		pdfDataBaixa.setWidth("160px");
		pdfDataBaixa.setHeight("-1px");
		absoluteLayout_1
				.addComponent(pdfDataBaixa, "top:150.0px;left:440.0px;");

		// pdfVencimentoGarantia
		pdfVencimentoGarantia = new PopupDateField();
		pdfVencimentoGarantia.setCaption("Data do vencimento da garantia:");
		pdfVencimentoGarantia.setImmediate(false);
		pdfVencimentoGarantia.setWidth("160px");
		pdfVencimentoGarantia.setHeight("-1px");
		absoluteLayout_1.addComponent(pdfVencimentoGarantia,
				"top:150.0px;left:660.0px;");

		// tfNumeroNotaFiscal
		tfNumeroNotaFiscal = new TextField();
		tfNumeroNotaFiscal.setCaption("Número da nota fiscal:");
		tfNumeroNotaFiscal.setImmediate(false);
		tfNumeroNotaFiscal.setWidth("160px");
		tfNumeroNotaFiscal.setHeight("-1px");
		absoluteLayout_1.addComponent(tfNumeroNotaFiscal,
				"top:200.0px;left:22.0px;");

		// tfChaveNfe
		tfChaveNfe = new TextField();
		tfChaveNfe.setCaption("Chave NFE:");
		tfChaveNfe.setImmediate(false);
		tfChaveNfe.setWidth("160px");
		tfChaveNfe.setHeight("-1px");
		absoluteLayout_1.addComponent(tfChaveNfe, "top:200.0px;left:230.0px;");

		// tfValorOriginal
		tfValorOriginal = new TextField();
		tfValorOriginal.setCaption("Valor original:");
		tfValorOriginal.setImmediate(false);
		tfValorOriginal.setWidth("160px");
		tfValorOriginal.setHeight("-1px");
		absoluteLayout_1.addComponent(tfValorOriginal,
				"top:200.0px;left:440.0px;");

		// tfValorCompra
		tfValorCompra = new TextField();
		tfValorCompra.setCaption("Valor da compra:");
		tfValorCompra.setImmediate(false);
		tfValorCompra.setWidth("160px");
		tfValorCompra.setHeight("-1px");
		absoluteLayout_1.addComponent(tfValorCompra,
				"top:200.0px;left:660.0px;");

		// tfValorAtualizado
		tfValorAtualizado = new TextField();
		tfValorAtualizado.setCaption("Valor atualizado:");
		tfValorAtualizado.setImmediate(false);
		tfValorAtualizado.setWidth("160px");
		tfValorAtualizado.setHeight("-1px");
		absoluteLayout_1.addComponent(tfValorAtualizado,
				"top:250.0px;left:22.0px;");

		// tfValorBaixa
		tfValorBaixa = new TextField();
		tfValorBaixa.setCaption("Valor da baixa:");
		tfValorBaixa.setImmediate(false);
		tfValorBaixa.setWidth("160px");
		tfValorBaixa.setHeight("-1px");
		absoluteLayout_1
				.addComponent(tfValorBaixa, "top:250.0px;left:230.0px;");

		// tfDeprecia
		tfDeprecia = new TextField();
		tfDeprecia.setCaption("Depreciação:");
		tfDeprecia.setImmediate(false);
		tfDeprecia.setWidth("160px");
		tfDeprecia.setHeight("-1px");
		absoluteLayout_1.addComponent(tfDeprecia, "top:250.0px;left:440.0px;");

		// tfMetodoDepreciacao
		tfMetodoDepreciacao = new TextField();
		tfMetodoDepreciacao.setCaption("Método de depreciação:");
		tfMetodoDepreciacao.setImmediate(false);
		tfMetodoDepreciacao.setWidth("160px");
		tfMetodoDepreciacao.setHeight("-1px");
		absoluteLayout_1.addComponent(tfMetodoDepreciacao,
				"top:250.0px;left:660.0px;");

		// pdfInicioDepreciacao
		pdfInicioDepreciacao = new PopupDateField();
		pdfInicioDepreciacao.setCaption("Início de depreciação:");
		pdfInicioDepreciacao.setImmediate(false);
		pdfInicioDepreciacao.setWidth("160px");
		pdfInicioDepreciacao.setHeight("-1px");
		absoluteLayout_1.addComponent(pdfInicioDepreciacao,
				"top:300.0px;left:22.0px;");

		// pdfUltimaDepreciacao
		pdfUltimaDepreciacao = new PopupDateField();
		pdfUltimaDepreciacao.setCaption("Última depreciação:");
		pdfUltimaDepreciacao.setImmediate(false);
		pdfUltimaDepreciacao.setWidth("160px");
		pdfUltimaDepreciacao.setHeight("-1px");
		absoluteLayout_1.addComponent(pdfUltimaDepreciacao,
				"top:300.0px;left:230.0px;");

		// tfTipoDepreciacao
		tfTipoDepreciacao = new TextField();
		tfTipoDepreciacao.setCaption("Tipo de depreciação:");
		tfTipoDepreciacao.setImmediate(false);
		tfTipoDepreciacao.setWidth("160px");
		tfTipoDepreciacao.setHeight("-1px");
		absoluteLayout_1.addComponent(tfTipoDepreciacao,
				"top:300.0px;left:440.0px;");

		// tfTaxaAnualDepreciacao
		tfTaxaAnualDepreciacao = new TextField();
		tfTaxaAnualDepreciacao.setCaption("Taxa anual de depreciação:");
		tfTaxaAnualDepreciacao.setImmediate(false);
		tfTaxaAnualDepreciacao.setWidth("160px");
		tfTaxaAnualDepreciacao.setHeight("-1px");
		absoluteLayout_1.addComponent(tfTaxaAnualDepreciacao,
				"top:300.0px;left:660.0px;");

		// tfTaxaMensalDepreciacao
		tfTaxaMensalDepreciacao = new TextField();
		tfTaxaMensalDepreciacao.setCaption("Taxa mensal de depreciação:");
		tfTaxaMensalDepreciacao.setImmediate(false);
		tfTaxaMensalDepreciacao.setWidth("160px");
		tfTaxaMensalDepreciacao.setHeight("-1px");
		absoluteLayout_1.addComponent(tfTaxaMensalDepreciacao,
				"top:350.0px;left:22.0px;");

		// tfTaxaDepreciacaoAcelerada
		tfTaxaDepreciacaoAcelerada = new TextField();
		tfTaxaDepreciacaoAcelerada.setCaption("Taxa de depreciação acelerada:");
		tfTaxaDepreciacaoAcelerada.setImmediate(false);
		tfTaxaDepreciacaoAcelerada.setWidth("160px");
		tfTaxaDepreciacaoAcelerada.setHeight("-1px");
		absoluteLayout_1.addComponent(tfTaxaDepreciacaoAcelerada,
				"top:350.0px;left:230.0px;");

		// tfTaxaDepreciacaoIncentivada
		tfTaxaDepreciacaoIncentivada = new TextField();
		tfTaxaDepreciacaoIncentivada
				.setCaption("Taxa de depreciação incentivada:");
		tfTaxaDepreciacaoIncentivada.setImmediate(false);
		tfTaxaDepreciacaoIncentivada.setWidth("160px");
		tfTaxaDepreciacaoIncentivada.setHeight("-1px");
		absoluteLayout_1.addComponent(tfTaxaDepreciacaoIncentivada,
				"top:350.0px;left:440.0px;");

		// tfFuncao
		tfFuncao = new TextField();
		tfFuncao.setCaption("Função:");
		tfFuncao.setImmediate(false);
		tfFuncao.setWidth("160px");
		tfFuncao.setHeight("-1px");
		absoluteLayout_1.addComponent(tfFuncao, "top:350.0px;left:660.0px;");

		// cbTipoAquisicao
		cbTipoAquisicao = new ComboBox();
		cbTipoAquisicao.setCaption("Tipo de aquisição:");
		cbTipoAquisicao.setImmediate(false);
		cbTipoAquisicao.setWidth("160px");
		cbTipoAquisicao.setHeight("-1px");
		cbTipoAquisicao.setRequired(true);
		absoluteLayout_1.addComponent(cbTipoAquisicao,
				"top:400.0px;left:660.0px;");

		// cbEstadoConservacao
		cbEstadoConservacao = new ComboBox();
		cbEstadoConservacao.setCaption("Estado de conservação:");
		cbEstadoConservacao.setImmediate(false);
		cbEstadoConservacao.setWidth("160px");
		cbEstadoConservacao.setHeight("-1px");
		cbEstadoConservacao.setRequired(true);
		absoluteLayout_1.addComponent(cbEstadoConservacao,
				"top:450.0px;left:22.0px;");

		// cbGrupoBem
		cbGrupoBem = new ComboBox();
		cbGrupoBem.setCaption("Grupo do bem:");
		cbGrupoBem.setImmediate(false);
		cbGrupoBem.setWidth("160px");
		cbGrupoBem.setHeight("-1px");
		cbGrupoBem.setRequired(true);
		absoluteLayout_1.addComponent(cbGrupoBem, "top:450.0px;left:230.0px;");

		// cbSetor
		cbSetor = new ComboBox();
		cbSetor.setCaption("Setor:");
		cbSetor.setImmediate(false);
		cbSetor.setWidth("160px");
		cbSetor.setHeight("-1px");
		cbSetor.setRequired(true);
		absoluteLayout_1.addComponent(cbSetor, "top:400.0px;left:22.0px;");

		// cbFornecedor
		cbFornecedor = new ComboBox();
		cbFornecedor.setCaption("Fornecedor:");
		cbFornecedor.setImmediate(false);
		cbFornecedor.setWidth("160px");
		cbFornecedor.setHeight("-1px");
		cbFornecedor.setRequired(true);
		absoluteLayout_1
				.addComponent(cbFornecedor, "top:400.0px;left:230.0px;");

		// cbColaborador
		cbColaborador = new ComboBox();
		cbColaborador.setCaption("Colaborador:");
		cbColaborador.setImmediate(false);
		cbColaborador.setWidth("160px");
		cbColaborador.setHeight("-1px");
		cbColaborador.setRequired(true);
		absoluteLayout_1.addComponent(cbColaborador,
				"top:400.0px;left:440.0px;");

		return absoluteLayout_1;
	}

	/**
	 * COMBOS
	 */

	public void carregarCmbTipoAquisicao(List<TipoAquisicaoEntity> lista) {
		BeanItemContainer<TipoAquisicaoEntity> bic = new BeanItemContainer<TipoAquisicaoEntity>(
				TipoAquisicaoEntity.class, lista);
		this.cbTipoAquisicao.setContainerDataSource(bic);
		this.cbTipoAquisicao.setItemCaptionPropertyId("nome");
	}

	public void carregarCmbEstadoConservacao(List<EstadoConservacaoEntity> lista) {
		BeanItemContainer<EstadoConservacaoEntity> bic = new BeanItemContainer<EstadoConservacaoEntity>(
				EstadoConservacaoEntity.class, lista);
		this.cbEstadoConservacao.setContainerDataSource(bic);
		this.cbEstadoConservacao.setItemCaptionPropertyId("nome");
	}

	public void carregarCmbGrupoBem(List<GrupoBemEntity> lista) {
		BeanItemContainer<GrupoBemEntity> bic = new BeanItemContainer<GrupoBemEntity>(
				GrupoBemEntity.class, lista);
		this.cbGrupoBem.setContainerDataSource(bic);
		this.cbGrupoBem.setItemCaptionPropertyId("nome");
	}

	public void carregarCmbSetor(List<Setor> lista) {
		BeanItemContainer<Setor> bic = new BeanItemContainer<Setor>(
				Setor.class, lista);
		this.cbSetor.setContainerDataSource(bic);
		this.cbSetor.setItemCaptionPropertyId("nome");
	}

	public void carregarCmbFornecedor(List<Fornecedor> lista) {
		BeanItemContainer<Fornecedor> bic = new BeanItemContainer<Fornecedor>(
				Fornecedor.class, lista);
		this.cbFornecedor.setContainerDataSource(bic);
		this.cbFornecedor.setItemCaptionPropertyId("nome");
	}

	public void carregarCmbColaborador(List<Colaborador> lista) {
		BeanItemContainer<Colaborador> bic = new BeanItemContainer<Colaborador>(
				Colaborador.class, lista);
		this.cbColaborador.setContainerDataSource(bic);
		this.cbColaborador.setItemCaptionPropertyId("nome");
	}

}