package dc.visao.adm.dotcompany;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;

public class ParametroClienteFormView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private TabSheet tabSheet_2;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private TextField txtCaminhoBanco;
	@AutoGenerated
	private TextField txtLideradoPorQuem;
	@AutoGenerated
	private TextField txtUsaNfe;
	@AutoGenerated
	private ComboBox cmbTipoSistema;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ParametroClienteFormView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, 0, 0);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(false);
		
		// tabSheet_2
		tabSheet_2 = buildTabSheet_2();
		horizontalLayout_1.addComponent(tabSheet_2);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_2() {
		// common part: create layout
		tabSheet_2 = new TabSheet();
		tabSheet_2.setImmediate(true);
		tabSheet_2.setWidth("100.0%");
		tabSheet_2.setHeight("100.0%");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		tabSheet_2.addTab(absoluteLayout_2, "Tab", null);
		
		return tabSheet_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("100.0%");
		
		// cmbTipoSistema
		cmbTipoSistema = new ComboBox();
		cmbTipoSistema.setCaption("Tipo de Sistema");
		cmbTipoSistema.setImmediate(false);
		cmbTipoSistema.setWidth("280px");
		cmbTipoSistema.setHeight("-1px");
		absoluteLayout_2
				.addComponent(cmbTipoSistema, "top:24.0px;left:19.0px;");
		
		// txtUsaNfe
		txtUsaNfe = new TextField();
		txtUsaNfe.setCaption("Usa NFE");
		txtUsaNfe.setImmediate(false);
		txtUsaNfe.setWidth("-1px");
		txtUsaNfe.setHeight("-1px");
		absoluteLayout_2.addComponent(txtUsaNfe, "top:24.0px;left:366.0px;");
		
		// txtLideradoPorQuem
		txtLideradoPorQuem = new TextField();
		txtLideradoPorQuem.setCaption("Liderado por Quem?");
		txtLideradoPorQuem.setImmediate(false);
		txtLideradoPorQuem.setWidth("280px");
		txtLideradoPorQuem.setHeight("-1px");
		absoluteLayout_2.addComponent(txtLideradoPorQuem,
				"top:68.0px;left:19.0px;");
		
		// txtCaminhoBanco
		txtCaminhoBanco = new TextField();
		txtCaminhoBanco.setCaption("Caminho do Banco");
		txtCaminhoBanco.setImmediate(false);
		txtCaminhoBanco.setWidth("293px");
		txtCaminhoBanco.setHeight("-1px");
		absoluteLayout_2.addComponent(txtCaminhoBanco,
				"top:68.0px;left:366.0px;");
		
		return absoluteLayout_2;
	}

}
